#!/usr/bin/env bash
#
#						build folders, files
#
# builds everything in monero-bash with default settings
build_Template()
{
	prompt_Sudo ; error_Sudo
	safety_HashList
	mkdir -p "$dotMoneroBash"
	permission_DotMoneroBash
	mkdir -p "$wallets"
	build_Config
	permission_DotMoneroBash
}

build_DotMoneroBash()
{
	build_Template
	mkdir -p "$bitMonero"
}

# just build monero-bash config
build_Config()
{
	prompt_Sudo ; error_Sudo
	safety_HashList
	cp -r "$installDirectory/config" "$config"
	permission_DotMoneroBash
}

build_Bin()
{
	prompt_Sudo ; error_Sudo
	safety_HashList
	sudo mkdir -p "$bin"
	permission_DotMoneroBash
}
