#!/usr/bin/env bash
#
#						build folders, files
#
# builds everything in monero-bash with default settings
build_Template()
{
	prompt_Sudo
	error_Sudo
	mkdir -p "$dotMoneroBash"
	mkdir -p "$wallets"
	build_Config
}

build_DotMoneroBash()
{
	build_Template
	mkdir -p "$bitMonero"
}

# just build monero-bash config
build_Config()
{
	prompt_Sudo
	error_Sudo
	sudo cp -r "$installDirectory/config" "$config"
	sudo chown -R "$USER:" "$config"
}

build_Bin()
{
	prompt_Sudo
	error_Sudo
	sudo mkdir -p "$bin"
	sudo mkdir -p "$binMonero"
	sudo mkdir -p "$binXMRig"
	sudo mkdir -p "$binP2Pool"
}
