#!/bin/bash
#
#						Check "x"
#						for fetching internet stats
check_Price()
{
	prompt_PriceAPI_IP
	$ired; echo "XMR price: " ;$off
	wget -qO- "https://min-api.cryptocompare.com/data/price?fsym=XMR&tsyms=USD,EUR,JPY,GBP,CHF,CAD,AUD,ZAR" \
	| tr -d "{\"}" | tr "," "\n" | sed 's/:/: /g'
	echo
	$bred; echo "XMR: 1"
}

check_NewVersion()
{
	local moneroLatestGithub="https://github.com/monero-project/monero/releases/latest"
	local moneroVar="https://downloads.getmonero.org/cli/monero-linux-x64-v*.*.*.*.*.*.*"
	local moneroTarName="monero-linux-x64-*.*"
	local mBashLatestGithub="https://github.com/hinto-janaiyo/monero-bash/releases/latest"
	local mBashVar="/hinto-janaiyo/monero-bash/releases/download/v*.*.*/monero-bash-v*.*.*"
	local mBashTarName="monero-bash-v*.*.*"
	monero_NewVer="$(wget -qO- "$moneroLatestGithub" | grep -o "$moneroVar" | grep -o "$moneroTarName" | awk '{print $1}' | sed 's/.tar.bz2\"//')"
	moneroBash_NewVer="$(wget -qO- "$mBashLatestGithub" | grep -o "$mBashVar" | grep -o "$mBashTarName" | awk '{print $1}' | sed 's/.tar\"//')"
}

check_Monero()
{
	prompt_Sudo
	check_NewVersion
	if [[ $MONERO_VER != $monero_NewVer ]]; then
		$white; echo -n "Monero: "
		$ired; echo -n "$MONERO_VER "
		$white; echo -n "> "
		$bgreen; echo "$monero_NewVer"
		updateFound="true"
		sudo sed -i "s@.*MONERO_OLD=.*@MONERO_OLD=\"true\"@" "$state"
	else
		$white; echo -n "Monero: "
		$bgreen; echo "up to date"
	fi
}

check_MoneroBash()
{
	prompt_Sudo
    if [[ $MONERO_BASH_VER != $moneroBash_NewVer ]]; then
        $white; echo -n "monero-bash: "
        $ired; echo -n "$MONERO_BASH_VER "
        $white; echo -n "> "
        $bgreen; echo "$moneroBash_NewVer"
		updateFound="true"
        sed -i "s@.*MONERO_BASH_OLD=.*@MONERO_BASH_OLD=\"true\"@" "$state"
    else
        $white; echo -n "monero-bash: "
        $bgreen; echo "up to date"
    fi
}

check_Update()
{
    check_Monero
    check_MoneroBash
    if [[ $updateFound = "true" ]]; then
        echo
        $ired; echo -n "monero-bash upgrade "
        $white; echo "to upgrade all"
        $white; echo -n "or: "
        $ired; echo -n "monero-bash upgrade <name> "
        $white; echo "to upgrade something specific"
        $off
    fi
}
