#!/usr/bin/env bash
#
#						messages for when hash/gpg is incorrect
#
compromised_hash_Monero()
{
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    $bwhite; echo -n "@   "
    $bred; echo -n "WARNING: HASH ERROR!"
    $bwhite; echo "                   @"
    $bwhite; echo "@                                          @"
    $bwhite; echo -n "@   "
    $bred; echo -n "[Monero] hash did not match!"
    $bwhite; echo "           @"
    $bwhite; echo -n "@   "
    $bred; echo -n "Monero might be compromised"
    $bwhite; echo "            @"
    $bwhite; echo -n "@   "
    $bred; echo -n "(or more likely, there was an error)"
    $bwhite; echo "   @"
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    echo "EXITING FOR SAFTEY..."
	exit
}

compromised_hash_MoneroBash()
{
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "@   "
	$bred; echo -n "WARNING: HASH ERROR!"
	$bwhite; echo "                   @"
	$bwhite; echo "@                                          @"
	$bwhite; echo -n "@   "
	$bred; echo -n "[monero-bash] hash did not match!"
	$bwhite; echo "      @"
	$bwhite; echo -n "@   "
	$bred; echo -n "hinto.janaiyo might be compromised"
	$bwhite; echo "     @"
	$bwhite; echo -n "@   "
	$bred; echo -n "(or more likely, there was an error)"
	$bwhite; echo "   @"
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	echo "EXITING FOR SAFTEY..."
	exit
}

compromised_hash_XMRig()
{
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "@   "
	$bred; echo -n "WARNING: HASH ERROR!"
	$bwhite; echo "                   @"
	$bwhite; echo "@                                          @"
	$bwhite; echo -n "@   "
	$bred; echo -n "[XMRig] hash did not match!"
	$bwhite; echo "            @"
	$bwhite; echo -n "@   "
	$bred; echo -n "XMRig might be compromised"
	$bwhite; echo "             @"
	$bwhite; echo -n "@   "
	$bred; echo -n "(or more likely, there was an error)"
	$bwhite; echo "   @"
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	echo "EXITING FOR SAFTEY..."
	exit
}

compromised_hash_P2Pool()
{
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "@   "
	$bred; echo -n "WARNING: HASH ERROR!"
	$bwhite; echo "                   @"
	$bwhite; echo "@                                          @"
	$bwhite; echo -n "@   "
    $bred; echo -n "[P2Pool] hash did not match!"
    $bwhite; echo "           @"
    $bwhite; echo -n "@   "
    $bred; echo -n "SChernykh might be compromised"
    $bwhite; echo "         @"
	$bwhite; echo -n "@   "
	$bred; echo -n "(or more likely, there was an error)"
	$bwhite; echo "   @"
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	echo "EXITING FOR SAFTEY..."
	exit
}
