#!/usr/bin/env bash
#
#						messages for when hash/gpg is incorrect
#
compromised_Hash()
{
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    $bred; echo "  WARNING: HASH ERROR!"
    $bred; echo "  [$NAME_PRETTY] hash did not match!"
    $bred; echo "  [$AUTHOR] might be compromised"
    $bred; echo  "  (or more likely, there was an error)"
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "ONLINE HASH: " ;$bblue; echo "$HASH"
	$bwhite; echo -n "LOCAL HASH: " ;$bred; echo "$LOCAL_HASH"
	echo "EXITING FOR SAFTEY..."
	[[ $VERBOSE = "true" ]]&& verbose_Upgrade
	exit
}

compromised_GPG()
{
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    $bblue; echo "  WARNING: GPG SIGNATURE ERROR!"
    $bblue; echo "  [$NAME_PRETTY] GPG Signature did not match!"
    $bblue; echo "  [$GPG_OWNER] might be compromised"
    $bblue; echo  "  (or more likely, there was an error)"
    $bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "ONLINE HASH: " ;$bblue; echo "$HASH"
	$bwhite; echo -n "LOCAL HASH: " ;$bred; echo "$LOCAL_HASH"
	$bwhite; echo "gpgSTDOUT: " ;$off; echo "$gpgSTDOUT"
	echo "EXITING FOR SAFTEY..."
	[[ $VERBOSE = "true" ]]&& verbose_Upgrade
	exit
}
