#!/usr/bin/env bash
# Monero Daemon Functions
daemon_start_Template()
{
	missing_MoneroDaemon
	if pgrep monerod &>/dev/null ; then
        $bred; echo "Monero daemon already detected..." ;$off
    else
		missing_ConfigMonerod
		DAEMON_COMMANDS
		error_Exit "Could not start monerod"
	fi
}

daemon_stop_Template()
{
	if pgrep monerod &>/dev/null ; then
		DAEMON_COMMANDS
	else
		$white; echo "Monero daemon: "
		$bred; echo -n "not online" ;$off
	fi
}
daemon_Start()
{
	DAEMON_COMMANDS()
	{
		$bred; echo "Starting Monero daemon..."
		missing_systemd_Monerod
		sudo systemctl start monero-bash-monerod
	}
	daemon_start_Template
}

daemon_Stop()
{
	DAEMON_COMMANDS()
	{
		$ired; echo "Stopping Monero daemon gracefully..." ;$off
		"$binMonero/monerod" --data-dir "$DATA_PATH" --config-file "$config/monerod.conf" exit
		for i in {1..30} ;do
			if [[ "$i" = "30" ]]; then
				print_Error "Monero daemon not responding, killing..."
				daemon_Kill
			fi
			if pgrep monerod &>/dev/null ;then
				echo -n "."
			else
				echo "."
				break
			fi
			sleep 1
		done
	}
	daemon_stop_Template
}

daemon_Kill()
{
	DAEMON_COMMANDS()
	{
		$ired; echo "Killing Monero daemon..."
		killall monerod
		if [[ $? = 0 ]]; then
			$white; echo "Monero daemon killed"
		else
			print_Error "Monero daemon was not killed"
		fi
	}
	daemon_stop_Template
}

daemon_start_Full()
{
	DAEMON_COMMANDS(){ "$binMonero/monerod" --data-dir "$DATA_PATH" --config-file "$config/monerod.conf" ;}
	daemon_start_Template
}
