#!/usr/bin/env bash
#
#						Monero Daemon Functions
#
daemon_StartAttached()
{
	missing_MoneroDaemon
	if pgrep monerod &>/dev/null ; then
		$bred; echo "Monero daemon detected..." ;$off
	else
		"$binMonero/monerod" --data-dir "$DATA_PATH" --config-file "$config/monerod"
	fi
}

daemon_StartDetached()
{
	missing_MoneroDaemon
	if pgrep monerod &>/dev/null ; then
		$bred; echo "Monero daemon detected..." ;$off
	else
		"$binMonero/monerod" --detach --data-dir "$DATA_PATH" --config-file "$config/monerod"
	fi
}

daemon_Stop()
{
	$ired; echo "Stopping Monero daemon gracefully..." ;$off
	"$binMonero/monerod" exit
	while pgrep monerod ;do
		echo -n "."
		sleep 1
	done
}

daemon_Kill()
{
	$ired; echo "Killing Monero daemon..."
	killall monerod
	if [[ $? = 0 ]]; then
		$white; echo "Monero daemon killed"
	else
		$ired; echo "error: Monero daemon was not killed"
	fi
}

daemon_Status()
{
	$white; echo -n "Monero daemon is: "
	if pgrep monerod &>/dev/null ;then
		$bgreen; echo "online"
		$binMonero/monerod status
	else
		$bred; echo "offline"
	fi
}
