#!/usr/bin/env bash
#
#						Download Functions
#
download_MoneroCLI()
{
	missing_MoneroCLIFolder
	prompt_Sudo
	error_Exit "Sudo is needed for downloading"
	wget -P "$tmp" -q --show-progress --content-disposition "https://downloads.getmonero.org/cli/linux64"
}

download_MoneroBash()
{
	prompt_Sudo
	error_Exit "Sudo is needed for downloading"
	local monerobash_link="$(wget -qO- https://github.com/hinto-janaiyo/monero-bash/releases/latest \
		| grep -o "/hinto-janaiyo/monero-bash/releases/download/.*/monero-bash-v.*" \
		| awk '{print $1}' \
		| sed 's/\"//')"
    wget -P "$tmp" -q --show-progress "$monerobash_link"
    Message_Red "verifying [monero-bash]"
    $off
    echo "$(wget -qO- https://github.com/hinto-janaiyo/monero-bash/releases/latest | grep -A1 "SHA256SUM" | awk '{print $1}' | head -n 2 | tail -n 1)" $mBash_tar | sha256sum -c
    if [[ $? = 0 ]]; then
        Message_Red "extracting [monero-bash]"
        tar -xf $mBash_tar
        rm -f $mBash_tar
        Version_Variables
        sed -i "s@.*MONERO_BASH_VER=.*@MONERO_BASH_VER=\""$moneroBash_NewVer"\"@" $config
        mBash_fol="$(ls | grep "monero-bash")"
        if [[ $OLD_FOLDER = "true" ]]; then
            mkdir -p "$old/$currentDayTime"
            mv "$installDirectory/monero-bash" "$old/$currentDayTime"
            mv "$mBash_fol/monero-bash" "$installDirectory/"
        else
            rm "$installDirectory/monero-bash"
            mv "$mBash_fol/monero-bash" "$installDirectory/"
        fi
        configDiffs="$(diff -y "$config" "$mBash_fol/config" | grep ">" | awk '{print $2}')"
        if [[ $configDiffs != "" ]]; then
            echo "# $moneroBash_NewVer options" >> $config
            diff -y "$config" "$mBash_fol/config" | grep ">" | awk '{print $2}' >> $config
        fi
        sed -i "s@.*MONERO_BASH_OLD=.*@MONERO_BASH_OLD=\"false\"@" $config
        rm -rf $tmp
    else
        Message_Red "[monero-hash] hash did not match! Either hinto.janaiyo has been compromised (or more likely, there was an error)"
        rm -rf $tmp
        exit
    fi
    cd $originalDirectory
}

download_XMRig()
{
	prompt_Sudo
	error_Exit "Sudo is needed for downloading"
	local xmrig_link="$(wget -qO- "https://github.com/xmrig/xmrig/releases/latest" \
		| grep -o "xmrig/xmrig/releases/download/.*/xmrig.*linux-static-x64.*" \
		| awk '{print $1}' \
		| sed 's/"//g')"
	sudo wget -P "$installDirectory" -q --show-progress "https://github.com/$xmrig_link"
}

download_All()
{
    $ibred; echo "Upgrading all..."
    Download_Monero_CLI
    Download_Monero_Bash
}
