#!/usr/bin/env bash
#
#						Error Handling Functions
#
error_Continue(){ [[ $? != "0" ]] && printf "\e[1;31m%s\e[0;97m%s\e[0m\n" "[monero-bash error] " "$1"; }

error_Exit() {
	if [[ $? != "0" ]]; then
		printf "\e[1;91m%s\e[0;97m%s\e[0m\n" "[monero-bash error] " "$1"
		printf "\e[1;91m%s\e[0m\n" "Exiting..."
		exit 1
	fi
}

error_Sudo()
{
	if [[ $? != "0" ]]; then
		printf "\e[1;91m%s\e[0;97m%s\e[0m\n" "[monero-bash error] " "[sudo] is needed"
		echo "Exiting..."
		exit 1
	fi
}


error_Unknown()
{
	printf "\e[1;91m%s\e[0;97m%s\e[0m\n" "[monero-bash error] " "Unknown command"
	exit 1
}

error_Trap()
{
	echo
	printf "\e[1;91m%s\e[1;97m%s\e[0m\n" "MONERO-BASH: " "EXIT SIGNAL DETECTED - $1"
}
