#!/usr/bin/env bash
# gpg functions for:
#	-toggling $VERIFY_GPG
# 	-importing gpgs keys and
#	-checking LOCAL/ONLINE diff
#	-overwriting LOCAL keys with ONLINE

gpg_Toggle()
{
	echo "GPG Verify is: "
	[[ $VERIFY_GPG = "true" ]]&&$bgreen&& echo "ON"
	[[ $VERIFY_GPG != "true" ]]&&$bred&& echo "OFF"
	$bwhite; echo "Toggle? " ;$off
	Yes()
	{
		prompt_Sudo ; error_Sudo
		[[ $VERIFY_GPG = "true" ]]&& sudo sed -i "s@.*VERIFY_GPG=.*@VERIFY_GPG=\"false\"@" "$state"
		[[ $VERIFY_GPG != "true" ]]&& sudo sed -i "s@.*VERIFY_GPG=.*@VERIFY_GPG=\"true\"@" "$state"
		echo "GPG Verify is now "
		[[ $VERIFY_GPG = "true" ]]&&$bgreen&& echo "ON"
		[[ $VERIFY_GPG != "true" ]]&&$bred&& echo "OFF"
	}
	No(){ echo "Exiting..." ;exit;}
	prompt_NOyes
}

gpg_import_Template()
{
	if [[ "$LOCAL" = "$ONLINE" ]]; then
		$bwhite; echo -n "$NAME: "
		$bgreen; echo "OK" ;$off
		gpg --import "$installDirectory/gpg/${NAME}.asc"
		echo
	else
		gpg_Diff
	fi
}

gpg_import_All()
{
	local NAME="binaryfate"
	local LOCAL="$(cat "$installDirectory/gpg/${NAME}.asc")"
	local LINK="https://raw.githubusercontent.com/monero-project/monero/master/utils/gpg_keys/binaryfate.asc"
	local ONLINE="$(wget -qO- "$LINK")"
	gpg_import_Template
	local NAME="hinto-janaiyo"
	local LOCAL="$(cat "$installDirectory/gpg/${NAME}.asc")"
	local LINK="https://raw.githubusercontent.com/hinto-janaiyo/monero-bash/master/gpg/hinto-janaiyo.asc"
	local ONLINE="$(wget -qO- "$LINK")"
	gpg_import_Template
	local NAME="SChernykh"
	local LOCAL="$(cat "$installDirectory/gpg/${NAME}.asc")"
	local LINK="https://p2pool.io/SChernykh.asc"
	local ONLINE="$(wget -qO- "$LINK")"
	gpg_import_Template
	local NAME="xmrig"
	local LOCAL="$(cat "$installDirectory/gpg/${NAME}.asc")"
	local LINK="https://raw.githubusercontent.com/xmrig/xmrig/master/doc/gpg_keys/xmrig.asc"
	local ONLINE="$(wget -qO- "$LINK")"
	gpg_import_Template
}

gpg_Diff()
{
	$bwhite; echo -n "The LOCAL and ONLINE gpg keys of "
	$bred; echo -n "$NAME "
	$bwhite; echo "are different!" ;$off
	$bblue; echo -n "LOCAL: "
	$white; echo "$installDirectory/gpg/${NAME}.asc"
	$bgreen; echo -n "ONLINE: "
	$white; echo "$LINK"
	while true ;do
		$bwhite; echo -n "What to do? [show / pick / skip] " ;$off
		read OPTION
		case $OPTION in
			show)
				$bblue; echo "LOCAL KEY:"
				$off; echo "$LOCAL"
				$bgreen; echo "ONLINE KEY:"
				$off; echo "$ONLINE"
				;;
			pick)
				while true; do
					$bwhite; echo -n "Which key to pick? [local / online] " ;$off
					read KEYPICK
					case $KEYPICK in
						local) gpg --import "$installDirectory/gpg/${NAME}.asc" && break ;;
						online) gpg_Overwrite && break ;;
						*) error_Continue "Invalid option"
					esac
				done
				break
				;;
			skip)
				$bwhite; echo "Skipping..."
				echo
				break
				;;
			*)
				error_Continue "Invalid option"
				;;
		esac
	done
}

gpg_Overwrite()
{
	prompt_Sudo
	error_Sudo
	$bwhite; echo "Overwriting LOCAL keys..." ;$off
	wget -q -O "$installDirectory/gpg/${NAME}.asc" "$LINK"
	code_Wget
	PRODUCE_HASH_LIST
	local LOCAL="$(cat "$installDirectory/gpg/${NAME}.asc")"
	gpg_import_Template
}
