#!/usr/bin/env bash
#
# gpg functions for:
#	-toggling $VERIFY_GPG="false/true"
# 	-importing gpgs keys
#	-checking LOCAL/ONLINE diff
#	-overwriting LOCAL keys with ONLINE

gpg_Toggle()
{
	echo -n "GPG Verify is: "
	[[ $VERIFY_GPG = "true" ]]&&$bgreen&& echo "ON"
	[[ $VERIFY_GPG != "true" ]]&&$bred&& echo "OFF"
	$bwhite; echo -n "Toggle? (y/N) " ;$off
	Yes()
	{
		prompt_Sudo ; error_Sudo
		safety_HashList
		trap "trap_GPG" 1 2 3 6 15
		[[ $VERIFY_GPG = "true" ]]&& sudo -u "$USER" sed -i "s@.*VERIFY_GPG=.*@VERIFY_GPG=\"false\"@" "$state" && PRODUCE_HASH_LIST
		[[ $VERIFY_GPG != "true" ]]&& sudo -u "$USER" sed -i "s@.*VERIFY_GPG=.*@VERIFY_GPG=\"true\"@" "$state" && PRODUCE_HASH_LIST
		source "$state"
		echo -n "GPG Verify is now "
		[[ $VERIFY_GPG = "true" ]]&&$bgreen&& echo "ON"
		[[ $VERIFY_GPG != "true" ]]&&$bred&& echo "OFF"
	}
	No(){ echo "Exiting..." ;exit;}
	prompt_NOyes
}

gpg_import_Template()
{
	local LOCAL="$(cat "$installDirectory/gpg/${GPG_OWNER}.asc")"
	local ONLINE="$(wget -qO- "$GPG_PUB_KEY")"
	if [[ "$LOCAL" = "$ONLINE" ]]; then
		$bwhite; echo -n "$GPG_OWNER: "
		$bgreen; echo "OK" ;$off
		gpg --import "$installDirectory/gpg/${GPG_OWNER}.asc"
		echo
	else
		gpg_Diff
	fi
}

gpg_import_Monero()
{
	define_Monero
	gpg_import_Template
}

gpg_import_MoneroBash()
{
	define_MoneroBash
	gpg_import_Template
}

gpg_import_XMRig()
{
	define_XMRig
	gpg_import_Template
}

gpg_import_P2Pool()
{
	define_P2Pool
	gpg_import_Template
}
gpg_import_All()
{
	gpg_import_Monero
	gpg_import_MoneroBash
	gpg_import_XMRig
	gpg_import_P2Pool
}

gpg_Diff()
{
	$bwhite; echo -n "The LOCAL and ONLINE gpg keys of "
	$bred; echo -n "$GPG_OWNER "
	$bwhite; echo "are different!" ;$off
	$bblue; echo -n "LOCAL: "
	$white; echo "$installDirectory/gpg/${GPG_OWNER}.asc"
	$bgreen; echo -n "ONLINE: "
	$white; echo "$GPG_PUB_KEY"
	while true ;do
		$bwhite; echo -n "What to do? [show / pick / skip] " ;$off
		read OPTION
		case $OPTION in
			show)
				$bblue; echo "LOCAL KEY:"
				$off; echo "$LOCAL"
				$bgreen; echo "ONLINE KEY:"
				$off; echo "$ONLINE"
				;;
			pick)
				while true; do
					$bwhite; echo -n "Which key to pick? [local / online] " ;$off
					read KEYPICK
					case $KEYPICK in
						local) gpg --import "$installDirectory/gpg/${GPG_OWNER}.asc" && break ;;
						online) gpg_Overwrite && break ;;
						*) error_Continue "Invalid option"
					esac
				done
				break
				;;
			skip)
				$bwhite; echo "Skipping..."
				echo
				break
				;;
			*)
				error_Continue "Invalid option"
				;;
		esac
	done
}

gpg_Overwrite()
{
	prompt_Sudo
	error_Sudo
	safety_HashList
	$bwhite; echo "Overwriting LOCAL keys..." ;$off
	trap "trap_Hash" 1 2 3 6 15
	wget -q -O "$installDirectory/gpg/${GPG_OWNER}.asc" "$GPG_PUB_KEY"
	code_Wget
	PRODUCE_HASH_LIST
	local LOCAL="$(cat "$installDirectory/gpg/${GPG_OWNER}.asc")"
	gpg_import_Template
}
