#!/usr/bin/env bash
# install functions
install_Template()
{
	if [[ "$NAME_VER" != "" ]]; then
		$white; echo -n "$NAME_PRETTY ($NAME_VER) "
		$white; echo "is already installed"
	else
		local INSTALL="true"
		upgrade_"$NAME_FUNC"
	fi
}

install_MoneroBash()
{
	define_MoneroBash
	echo "Uhh... It's already installed..."
	echo -n "$NAME_PRETTY ($NAME_VER) "
}

install_Monero()
{
	define_Monero
	install_Template
}

install_XMRig()
{
	define_XMRig
	install_Template
}

install_P2Pool()
{
	define_P2Pool
	install_Template
}

install_All()
{
	[[ $MONERO_VER = "" ]]&& install_Monero
	[[ $XMRIG_VER = "" ]]&& install_XMRig
	[[ $P2POOL_VER = "" ]]&& install_P2Pool
}
