#!/usr/bin/env bash
# install functions
install_Template()
{
	if [[ "$NAME_VER" != "" ]]; then
		$white; echo -n "$NAME_PRETTY ($NAME_VER) "
		$white; echo "is already installed"
	else
		local INSTALL="true"
		upgrade_"$NAME_FUNC"
	fi
}

install_Monero()
{
	define_Monero
	install_Template
}

install_XMRig()
{
	define_XMRig
	install_Template
}

install_P2Pool()
{
	define_P2Pool
	install_Template
}

install_All()
{
	install_Monero
	install_XMRig
	install_P2Pool
}
