#!/usr/bin/env bash
# install functions
install_Template()
{
	if [[ "$NAME_VER" != "" ]]; then
		$white; echo -n "$NAME_PRETTY ($NAME_VER) "
		$white; echo "is already installed"
	else
		local INSTALL="true"
		upgrade_"$NAME_FUNC"
	fi
}

install_Monero()
{
	define_Monero
	install_Template
}

install_XMRig()
{
	define_XMRig
	install_Template
}

install_P2Pool()
{
	define_P2Pool
	install_Template
}

install_All()
{
	$bwhite; printf "Packages to install: " ;$off
	[[ $MONERO_BASH_VER != "" ]]&& printf " [monero-bash] "
	[[ $MONERO_VER != "" ]]&& printf " [Monero] "
	[[ $XMRIG_VER != "" ]]&& printf " [XMRig] "
	[[ $P2POOL_VER != "" ]]&& printf " [P2Pool] "
	echo;echo
	$bwhite; echo -n "Install? (Y/n) " ;$off
	Yes()
	{
		[[ $MONERO_VER != "" ]]&& install_Monero
		[[ $XMRIG_VER != "" ]]&& install_XMRig
		[[ $P2POOL_VER != "" ]]&& install_P2Pool
	}
	No(){ echo "Exiting..." ;exit;}
	prompt_YESno
}
