#!/usr/bin/env bash
#
#                       Prompt/Message Functions
#
YES_no()
{
	read yn
	if [[ $yn = "" || $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	else
		No
	fi
}

yes_NO()
{
	read yn
	if [[ $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	elif [[ $yn = "" ]]; then
		No
	else
		No
	fi
}

Message()
{
	echo
	$igreen; echo "###### $1" ;$off
}

Message_Red()
{
	$ired; echo "###### $1" ;$off
}

Monero_Bash_Title()
{
	$bred; echo "###################"
	$bred; echo "#   monero-bash   #"
	$bred; echo "###################"
	$off
}

Seed_Language_List()
{
cat <<EOM
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
11 : Lojban
EOM
}
