#!/usr/bin/env bash
#
# all-in-one mining functions
# combines multiple functions
# that invoke monerod,xmrig,p2pool
#

mine_Start()
{
	missing_Monero
	missing_XMRig
	missing_P2Pool
	if [[ "$MINE_UNCONFIGURED" = "true" ]]; then
		mine_Config
	else
		prompt_Sudo ; error_Sudo
		daemon_Start
		p2pool_Start
		xmrig_Start
		printf "Watch with: "
		$bwhite; echo "monero-bash watch <daemon/p2pool/xmrig>"
	fi
}

mine_Stop()
{
	prompt_Sudo ; error_Sudo
	daemon_Stop
	p2pool_Stop
	xmrig_Stop
}

mine_Config()
{
    $bred; echo "###########################################################"
    $bred; echo "#            monero-bash mining configuration             #"
    $bred; echo "###########################################################"
	$bwhite; printf "WALLET ADDRESS: " ;$off
	read WALLET_INTERACTIVE
	$bwhite; printf "DAEMON IP [default - 127.0.0.1]: " ;$off
	read IP
	$bwhite; printf "POOL IP [default - 127.0.0.1:3333]: " ;$off
	read POOL
	$bwhite; printf "Use P2Pool Mini-Pool? (Y/n): " ;$off
	Yes(){ MINI="true" ;}
	No(){ MINI="false" ;}
	prompt_YESno
	$bblue; printf "WALLET ADDRESS: " ;$off; echo "$WALLET_INTERACTIVE"
	$bblue; printf "DAEMON IP: " ;$off
	if [[ "$IP" = "" ]]; then
		echo "127.0.0.1"
		IP="127.0.0.1"
	else
		echo "$IP"
	fi
	$bblue; printf "POOL IP: " ;$off
	if [[ "$POOL" = "" ]]; then
		echo "127.0.0.1:3333"
		POOL="127.0.0.1:3333"
	else
		echo "$POOL"
	fi
	$bblue; printf "P2POOL MINI: " ;$off
		echo "$MINI"
	$bwhite; printf "Use these settings? (Y/n) "
	Yes()
	{
		prompt_Sudo ; error_Sudo
		safety_HashList
		trap "trap_No" 1 2 3 6 15

	    define_P2Pool
		if [[ "$MINI" = "true" ]]; then
			export COMMAND="$binP2Pool/p2pool --host $IP --wallet $WALLET_INTERACTIVE --loglevel 2 --mini"
		else
			export COMMAND="$binP2Pool/p2pool --host $IP --wallet $WALLET_INTERACTIVE --loglevel 2"
		fi
	    systemd_Template

		echo "Editing monero-bash.conf..."
		sudo sed -i "s@.*DAEMON_IP.*@DAEMON_IP=\"$IP\"@" "$config/monero-bash.conf"
		sudo sed -i "s@.*WALLET.*@WALLET=\"$WALLET\"@" "$config/monero-bash.conf"
		echo "Editing xmrig.json..."
		sudo sed -i "s@.*user.*@            \"user\": \"$WALLET\",@" "$xmrigConf"
		sudo sed -i "s@.*url.*@            \"url\": \"$POOL\",@" "$xmrigConf"
		sudo sed -i "s@.*MINE_UNCONFIGURED.*@MINE_UNCONFIGURED=\"false\"@" "$state"
		PRODUCE_HASH_LIST
		$bgreen; echo "Mining configuration complete"
		$white; echo -n "To get started: "
		$bwhite; echo "monero-bash mine start"
	}
	No(){ echo "Exiting..." ;exit;}
	prompt_YESno
}
