#!/usr/bin/env bash
#
#							Missing "x" Functions
#
missing_MoneroDaemon()
{
	if [[ ! -f "$binMonero/monerod" ]]; then
		error_Exit "monerod missing!"
	fi
}

missing_MoneroCLI()
{
	if [[ ! -f "$binMonero/monero-wallet-cli" ]]; then
		error_Exit "monero-wallet-cli missing!"
	fi
}

missing_BinMonero()
{
	if [[ ! -d "$binMonero" ]]; then
		error_Exit "$binMonero missing!"
	fi
}

missing_P2Pool()
{
	if [[ ! -f "$binP2Pool/p2pool" ]]; then
		error_Exit "P2Pool missing!"
	fi
}

missing_XMRig()
{
	if [[ ! -f "$binXMRig/xmrig" ]]; then
		error_Exit "XMRig missing!"
    fi
}

missing_DotMoneroBash()
{
	if [[ ! -d "$dotMoneroBash" ]]; then
		error_Exit "$dotMoneroBash missing!"
		echo "Create one with default settings? (Y/n) "
		Yes(){ build_DefaultDotMoneroBash ;}
		No(){ echo "Skipping..." ;}
		prompt_YESno
	fi
}

missing_Wallets()
{
	if [[ ! -d "$wallets" ]]; then
		print_Error "$wallets missing!"
		echo "Creating wallet folder..."
		mkdir "$wallets"
	fi
}

missing_ConfigFolder()
{
	if [[ ! -d "$config" ]]; then
		print_Error "$config missing!"
		echo "Creating default config folder..."
		build_Config
	fi
}

missing_ConfigTemplate()
{
	if [[ ! -f "$config/$conf" ]]; then
		print_Error "$conf missing!"
		echo "Creating default $conf..."
		sudo cp "$installDirectory/config/$conf" "$config/$conf"
	fi
}

missing_ConfigMonerod()
{
	local conf="monerod.conf"
	missing_ConfigTemplate
}

missing_ConfigWallet()
{
	local conf="monero-wallet-cli.conf"
	missing_ConfigTemplate
}


missing_ConfigMoneroBash()
{
	local conf="monero-bash.conf"
	missing_ConfigTemplate
}


missing_ConfigXMRig()
{
	local conf="xmrig.json"
	missing_ConfigTemplate
}


missing_ConfigP2Pool()
{
	local conf="p2pool.json"
	missing_ConfigTemplate
}

missing_ConfigAll()
{
	missing_ConfigMoneroBash
	[[ $MONERO_VER != "" ]]&& missing_ConfigMonerod && missing_ConfigWallet
	[[ $XMRIG_VER != "" ]]&& missing_ConfigXMRig
	[[ $P2POOL_VER != "" ]]&& missing_ConfigP2Pool
}

missing_systemd_Monerod()
{
	if [[ $SYSTEMD_MONEROD = "true" && ! -f /etc/systemd/system/monero-bash-monerod.service ]]; then
		error_Continue "monero-bash-monerod.service missing!"
		$bwhite; echo "To make one: "
		$bred; echo "monero-bash mine configure"
		exit
	fi
}

missing_systemd_XMRig()
{
	if [[ ! -f /etc/systemd/system/monero-bash-xmrig.service ]]; then
		error_Continue "monero-bash-xmrig.service missing!"
		$bwhite; echo "To make one: "
		$bred; echo "monero-bash mine configure"
		exit
	fi
}

missing_systemd_P2Pool()
{
	if [[ ! -f /etc/systemd/system/monero-bash-p2pool.service ]]; then
		error_Continue "monero-bash-p2pool.service missing!"
		$bwhite; echo "To make one: "
		$bred; echo "monero-bash mine configure"
		exit
	fi
}

