#!/usr/bin/env bash
#
#							Missing "x" Functions
#
missing_MoneroDaemon()
{
	if [[ ! -f "$binMonero/monerod" ]]; then
		print_Error_Exit "monerod missing!"
	fi
}

missing_MoneroCLI()
{
	if [[ ! -f "$binMonero/monero-wallet-cli" ]]; then
		print_Error_Exit "monero-wallet-cli missing!"
	fi
}

missing_BinMonero()
{
	if [[ ! -d "$binMonero" ]]; then
		print_Error_Exit "$binMonero missing!"
	fi
}

missing_P2Pool()
{
	if [[ ! -f "$binP2Pool/p2pool" ]]; then
		print_Error_Exit "P2Pool missing!"
	fi
}

missing_XMRig()
{
	if [[ ! -f "$binXMRig" ]]; then
		print_Error_Exit "XMRig missing!"
    fi
}

missing_DotMoneroBash()
{
	if [[ ! -d "$dotMoneroBash" ]]; then
		print_Error_Exit "$dotMoneroBash missing!"
		echo "Create one with default settings? (Y/n) "
		Yes(){ build_DefaultDotMoneroBash ;}
		No(){ echo "Skipping..." ;}
		prompt_YESno
	fi
}

missing_Wallets()
{
	if [[ ! -d "$wallets" ]]; then
		print_Error "$wallets missing!"
		echo "Creating wallet folder..."
		mkdir "$wallets"
	fi
}

missing_ConfigFolder()
{
	if [[ ! -d "$config" ]]; then
		print_Error "$config missing!"
		echo "Creating default config folder..."
		build_Config
	fi
}

missing_ConfigTemplate()
{
	if [[ ! -f "$config/$conf" ]]; then
		print_Error "$conf missing!"
		echo "Creating default $conf..."
		sudo cp "$installDirectory/config/$conf" "$config/$conf"
	fi
}

missing_ConfigMonerod()
{
	local conf="monerod.conf"
	missing_ConfigTemplate
}

missing_ConfigWallet()
{
	local conf="monero-wallet-cli.conf"
	missing_ConfigTemplate
}


missing_ConfigMoneroBash()
{
	local conf="monero-bash.conf"
	missing_ConfigTemplate
}


missing_ConfigXMRig()
{
	local conf="xmrig.json"
	missing_ConfigTemplate
}


missing_ConfigP2Pool()
{
	local conf="p2pool.json"
	missing_ConfigTemplate
}
