#!/usr/bin/env bash
#
#						monero-bash Functions
#

###################################################   START OF INSTALL FUNCTION   ###################################################
monerobash_Install()
{
	$bred; echo "###################################################################"
	$bred; echo "#            monero-bash configuration & installation             #"
	$bred; echo "###################################################################"

while true ;do
	# Data Path
	# $HOME/.bitmonero check
	if [[ -d "$HOME/.bitmonero" ]]; then
		$ired; echo "Monero data folder detected"
		$white; echo -n "Use "
		$ired; echo -n "$HOME/.bitmonero"
		$white; echo -n "? (Y/n): " ;$iwhite
		Yes(){ alreadyFoundDataPath="true" ;}
		No(){ :;}
		prompt_YESno
	fi
	if [[ $alreadyFoundDataPath != "true" ]]; then
		$white; echo -n "Monero data path [Enter for default]: " ;$iwhite
		read inputData
	fi

	# Data Path Confirmation
	if [[ $alreadyFoundDataPath = "true" ]]; then
		$white; echo -n "Data path: "
		$ired; echo "$HOME/.bitmonero"
		$white; echo -n "Is this okay? (Y/n) "
		Yes(){ echo "Data path set!" ;yes="true";}
		No(){ :;}
		prompt_YESno
	elif [[ $alreadyFoundDataPath != "true" ]]; then
		$white; echo -n "Data path: "
		if [[ "$inputData" = "" ]]; then
			$ired; echo "$bitMonero"
		else
			$ired; echo "$inputData"
		fi
		$white; echo -n "Is this okay? (Y/n) "
		Yes(){ echo "Data path set!" ;yes="true";}
		No(){ :;}
		prompt_YESno
	fi
	[[ "$yes" = "true" ]]&& break
done

# Installation Prompt
	$bwhite; echo -n "Start "
	$bred; echo -n "monero-bash "
	$bwhite; echo -n "install? (Y/n) "
	Yes(){ $white; echo "Starting..." ;}
	No(){ $white; echo "Exiting..." ;exit;}
	prompt_YESno
	prompt_Sudo
	error_Exit "Sudo is required to install monero-bash"

# Hash Integrity Check
	print_GreenHash "Checking monero-bash hash integrity"
	CHECK_HASH_LIST
	alreadyCheckedHashList="true"

# TRAP
trap "trap_No" 1 2 3 6 15

# Deleting Git Files
	print_GreenHash "Cleaning up git files"
	[[ -d "$installDirectory/.git" ]]&& sudo rm -r "$installDirectory/.git"
	[[ -f "$installDirectory/.gitignore" ]]&& sudo rm -r "$installDirectory/.gitignore"
	[[ -f "$installDirectory/LICENSE" ]]&& sudo rm "$installDirectory/LICENSE"
	[[ -f "$installDirectory/README.md" ]]&& sudo rm "$installDirectory/README.md"
	[[ -f "$installDirectory/CHANGELOG.md" ]]&& sudo rm "$installDirectory/CHANGELOG.md"
	[[ -d "$installDirectory/docs" ]]&& sudo rm -r "$installDirectory/docs"
	[[ -d "$installDirectory/.old" ]]&& sudo rm -r "$installDirectory/.old"
	[[ -d "$installDirectory/tests" ]]&& sudo rm -r "$installDirectory/tests"

# Moving to /usr/local/
	print_GreenHash "Installing monero-bash in /usr/local/share/monero-bash/"
	sudo mv "$installDirectory" "/usr/local/share/"
	installDirectory="/usr/local/share/monero-bash"
	hashlist="$installDirectory/src/txt/hashlist"
	state="$installDirectory/src/txt/state"

# Adding to PATH
	print_GreenHash "Adding monero-bash to PATH"
	path_Add

# Building $HOME/.monero-bash
	print_GreenHash "Building /.monero-bash/ folders"
	if [[ $alreadyFoundDataPath = "true" ]]; then
		build_Template
	else
		build_DotMoneroBash
	fi

# Setting Data Path
	print_GreenHash "Setting data path"
	if [[ $alreadyFoundDataPath = "true" ]]; then
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$HOME/.bitmonero"\"@" "$config/monero-bash.conf"
	elif [[ $inputData != "" ]]; then
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$inputData"\"@" "$config/monero-bash.conf"
	else
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$bitMonero"\"@" "$config/monero-bash.conf"
	fi
	source "$config/monero-bash.conf"

# First Time = false , Set Installed User , chown
sudo sed -i "s@.*FIRST_TIME.*@FIRST_TIME=\"false\"@" "$state"
sudo sed -i "s@.*INSTALLED_USER.*@INSTALLED_USER=\"$USER\"@" "$state"
sudo chown -R "$USER:$USER" "$installDirectory"
sudo chmod 700 "$installDirectory"
sudo chmod 700 "$dotMoneroBash"
PRODUCE_HASH_LIST

#
#                       End
#
echo
$bred; echo "###################################################################"
$bred; echo "#                monero-bash installation complete                #"
$bred; echo "###################################################################"
$bwhite; echo -n "monero-bash path: " ;$white; echo "$dotMoneroBash"
$white; echo "Data: $DATA_PATH"
echo "Configs: $config"
echo "Wallets: $wallets"
echo
$white; echo -n "type: "
$bred; echo -n "monero-bash help "
$white; echo "to get started"
}
###################################################   END OF INSTALL FUNCTION   ###################################################

monerobash_Uninstall()
{
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "@   "
	$bred; echo -n "THIS WILL UNINSTALL monero-bash, DELETE /.monero-bash/ AND EVERYTHING INSIDE IT"
	$bwhite; echo "   @"
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "Uninstall "
	$ired; echo -n "monero-bash? "
	$bwhite; echo -n "(y/N) "
	Yes()
	{
		walletCount="$(ls "$wallets" | wc -l)"
		if [[ "$walletCount" > "0" ]]; then
			echo
			$bwhite; echo -n "@@@@@@@@@@@@"
			$bred; echo -n "      WALLETS FOUND      "
			$bwhite; echo "@@@@@@@@@@@@"
			$bwhite; ls "$wallets"
			$bred; echo -n "ARE YOU SURE YOU WANT TO UNINSTALL? (y/N) " ;$bwhite
			Yes(){ : ;}
			No(){ $white; echo "Exiting..." ;exit;}
			prompt_NOyes
		fi
		prompt_Sudo
		error_Exit "Sudo is needed to uninstall"
		for i in {10..0} ;do
		tput sc
		if [[ "$i" = "0" ]]; then
			$bred; echo -n "Uninstalling..."
		else
			$bred; echo -n "Uninstalling in $i..."
		fi
		sleep 1
		if [[ $i != "0" ]]; then
		tput rc;tput el
		else
		echo;echo
		fi
		done
		# Hash Integrity Check
		print_GreenHash "Checking monero-bash hash integrity"
		QUIET_HASH_LIST
		trap "trap_No" 1 2 3 6 15
		mine_Stop
		print_WhiteHash "Removing $dotMoneroBash"
			sudo rm -rf "$dotMoneroBash"
			error_Exit "$dotMoneroBash not removed"
		print_WhiteHash "Removing from PATH"
			path_Remove
			error_Exit "PATH not removed"
		print_WhiteHash "Removing /usr/local/share/monero-bash/"
			sudo rm -rf "/usr/local/share/monero-bash"
			error_Exit "monero-bash not removed"
		print_WhiteHash "Removing systemd services"
			define_Monero
				[[ -e "$sysd/$SERVICE" ]]&& sudo rm "$sysd/$SERVICE"
				error_Continue "$SERVICE not removed"
			define_XMRig
				[[ -e "$sysd/$SERVICE" ]]&& sudo rm "$sysd/$SERVICE"
				error_Continue "$SERVICE not removed"
			define_P2Pool
				[[ -e "$sysd/$SERVICE" ]]&& sudo rm "$sysd/$SERVICE"
				error_Continue "$SERVICE not removed"
		print_GreenHash "monero-bash has been uninstalled"
	}
	No(){ $white; echo "Exiting..." ;exit;}
	prompt_NOyes
}
