#!/usr/bin/env bash
#
#						monero-bash Functions
#

###################################################   START OF INSTALL FUNCTION   ###################################################
monerobash_Install()
{
	$bred; echo "###################################################################"
	$bred; echo "#            monero-bash configuration & installation             #"
	$bred; echo "###################################################################"

while true ;do
	# Data Path
	# $HOME/.bitmonero check
	if [[ -d "$HOME/.bitmonero" ]]; then
		$ired; echo "Monero data folder detected"
		$white; echo -n "Use "
		$ired; echo -n "$HOME/.bitmonero"
		$white; echo -n "? (Y/n): " ;$iwhite
		Yes(){ alreadyFoundDataPath="true" ;}
		No(){ :;}
		prompt_YESno
	fi
	if [[ $alreadyFoundDataPath != "true" ]]; then
		$white; echo -n "Monero data path [Enter for default]: " ;$iwhite
		read inputData
	fi

	# Data Path Confirmation
	if [[ $alreadyFoundDataPath = "true" ]]; then
		$white; echo -n "Data path: "
		$ired; echo "$HOME/.bitmonero"
		$white; echo -n "Is this okay? (Y/n) "
		Yes(){ echo "Data path set!" ;yes="true";}
		No(){ :;}
		prompt_YESno
	elif [[ $alreadyFoundDataPath != "true" ]]; then
		$white; echo -n "Data path: "
		if [[ "$inputData" = "" ]]; then
			$ired; echo "$bitMonero"
		else
			$ired; echo "$inputData"
		fi
		$white; echo -n "Is this okay? (Y/n) "
		Yes(){ echo "Data path set!" ;yes="true";}
		No(){ :;}
		prompt_YESno
	fi
	[[ "$yes" = "true" ]]&& break
done

# Installation Prompt
	$bwhite; echo -n "Start "
	$bred; echo -n "monero-bash "
	$bwhite; echo -n "install? (Y/n) "
	Yes(){ $white; echo "Starting..." ;}
	No(){ $white; echo "Exiting..." ;exit;}
	prompt_YESno
	prompt_Sudo
	error_Exit "Sudo is required to install monero-bash"

# Hash Integrity Check
	print_GreenHash "Checking monero-bash hash integrity"
	CHECK_HASH_LIST

# Moving to /usr/local/
	print_GreenHash "Installing monero-bash in /usr/local/share/monero-bash/"
	sudo mv "$installDirectory" "/usr/local/share/" &&
	installDirectory="/usr/local/share/monero-bash" &&
	hashlist="$installDirectory/src/txt/hashlist" &&
	state="$installDirectory/src/txt/state"

# Adding to PATH
	print_GreenHash "Adding monero-bash to PATH"
	path_Add

# Building $HOME/.monero-bash
	print_GreenHash "Building /.monero-bash/ folders"
	if [[ $alreadyFoundDataPath = "true" ]]; then
		build_NoBitMonero_DotMoneroBash
	else
		build_DefaultDotMoneroBash
	fi

# Setting Data Path
	print_GreenHash "Setting data path"
	if [[ $alreadyFoundDataPath = "true" ]]; then
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$HOME/.bitmonero"\"@" "$config/monero-bash.conf"
	elif [[ $inputData != "" ]]; then
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$inputData"\"@" "$config/monero-bash.conf"
	else
		sed -i "s@.*DATA_PATH.*@DATA_PATH=\""$bitMonero"\"@" "$config/monero-bash.conf"
	fi
	source "$config/monero-bash.conf"

# First Time = false
sudo sed -i "s@.*FIRST_TIME.*@FIRST_TIME=\"false\"@" "$state"
sudo chown -R "$USER:" "$installDirectory"
PRODUCE_HASH_LIST

#
#                       End
#
echo
$bred; echo "###################################################################"
$bred; echo "#                monero-bash installation complete                #"
$bred; echo "###################################################################"
$bwhite; echo -n "monero-bash path: " ;$white; echo "$dotMoneroBash"
$white; echo "Data: $DATA_PATH"
echo "Binaries: $bin"
echo "Configs: $config"
echo "Wallets: $wallets"
echo
$white; echo -n "type: "
$bred; echo -n "monero-bash help "
$white; echo "to get started"
}
###################################################   END OF INSTALL FUNCTION   ###################################################

monerobash_Uninstall()
{
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "@   "
	$bred; echo -n "THIS WILL UNINSTALL monero-bash, DELETE /.monero-bash/ AND EVERYTHING INSIDE IT"
	$bwhite; echo "  @"
	$bwhite; echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	$bwhite; echo -n "Uninstall "
	$ired; echo -n "monero-bash? "
	$bwhite; echo -n "(y/N) "
	Yes()
	{
		prompt_Sudo
		error_Exit "Sudo is needed to uninstall"
		for i in {10..1} ;do
		tput sc
		$bred; echo -n "Uninstalling in $i..."
		sleep 1
		if [[ $i != "1" ]]; then
		tput rc;tput el
		else
		echo;echo
		fi
		done
		# Hash Integrity Check
		print_GreenHash "Checking monero-bash hash integrity"
		QUIET_HASH_LIST
		print_RedHash "Removing $dotMoneroBash"
			sudo rm -rf "$dotMoneroBash"
			error_Continue "$dotMoneroBash not removed"
		print_RedHash "Removing from PATH"
			path_Remove
			error_Continue "PATH not removed"
		print_RedHash "Removing /usr/local/share/monero-bash/"
			sudo rm -rf "/usr/local/share/monero-bash"
			error_Exit "monero-bash not removed"
		print_GreenHash "monero-bash has been uninstalled"
	}
	No(){ $white; echo "Exiting..." ;}
	prompt_NOyes
}
