#!/usr/bin/env bash
#
#						monero-bash Functions
#
Print_Usage()
{
	$off; echo -n "monero-bash usage: "
	$ired; echo "monero-bash <option> <more options>" ;$off
	echo
	cat "$installDirectory/src/usage"
	echo
	$ired; echo -n "monero-bash, "
	$white; echo -n "made by: "
	$bgreen; echo "hinto.janaiyo"
}

Price_Check()
{
	$ired; echo "Monero price: " ;$off
	wget -qO- "https://min-api.cryptocompare.com/data/price?fsym=XMR&tsyms=USD,EUR" | tr -d "{\"}" | tr "," "\n"
	echo
}

Current_Versions()
{
		$white; echo -n "Monero-CLI: "
	if [[ $MONERO_CLI_OLD = "false" ]]; then
		$bgreen; echo "$MONERO_CLI_VER"
	else
		$bred; echo "$MONERO_CLI_VER"
	fi
		$white; echo -n "monero-bash: "
	if [[ $MONERO_BASH_OLD = "false" ]]; then
		$bgreen; echo "$MONERO_BASH_VER"
	else
		$bred; echo "$MONERO_BASH_VER"
	fi
}

Add_To_Bashrc()
{
	echo "export PATH="\$PATH:$installDirectory" # $sha256" >> $HOME/.bashrc
}

Remove_From_Bashrc()
{
	echo $pathSha
	sed -i "s@.*$pathSha.*@@g" "$HOME/.bashrc"
}

Reset_Path()
{
	$white; echo -n "Resetting "
	$ired; echo -n "monero-bash "
	$white; echo "PATH..."
	Remove_From_Bashrc
	Add_To_Bashrc &&
	$bgreen&& echo "Reset PATH!"
}

Uninstall()
{
	$bred; echo "### THIS WILL DELETE /monero-bash/ AND EVERYTHING INSIDE IT ###"
	$bwhite; echo -n "Uninstall "
	$ired; echo -n "monero-bash? "
	$bwhite; echo -n "(y/N) "
	Yes()
	{
		for i in {10..1} ;do
		tput sc
		$bred; echo -n "Uninstalling in $i..."
		sleep 1
		if [[ $i != "1" ]]; then
		tput rc;tput el
		else
		echo;echo
		fi
		done
		Message_Red "Removing from PATH"
		Remove_From_Bashrc
		Message_Red "Removing /monero-bash/"
		rm -rf $installDirectory
	}
	No(){ $white; echo "Exiting..." ;}
	yes_NO
}
