#!/usr/bin/env bash

p2pool_start_Template()
{
	missing_P2Pool
	if pgrep p2pool &>/dev/null ; then
        $bred; echo "P2Pool already detected..." ;$off
    else
		$bgreen; echo "Starting P2Pool..." ;$off
		COMMANDS
		error_Exit "Could not start P2Pool"
	fi
}

p2pool_stop_Template()
{
	if pgrep p2pool &>/dev/null ; then
		COMMANDS
	else
		$white; echo -n "P2Pool: "
		$bred; echo "not online" ;$off
	fi
}

p2pool_Start()
{
	COMMANDS()
	{
		missing_systemd_P2Pool
		sudo systemctl start monero-bash-p2pool
	}
	p2pool_start_Template
}

p2pool_Stop()
{
	COMMANDS()
	{
		$ired; echo "Stopping P2Pool gracefully..." ;$off
		sudo systemctl stop monero-bash-p2pool
		for i in {1..30} ;do
			if [[ "$i" = "30" ]]; then
				echo
				print_Error "P2Pool not responding, killing..."
				p2pool_Kill
			fi
			if pgrep p2pool &>/dev/null ;then
				echo -n "."
			else
				echo "."
				break
			fi
			sleep 1
		done
	}
	p2pool_stop_Template
}

p2pool_Kill()
{
	COMMANDS()
	{
		$ired; echo "Killing P2Pool..."
		killall p2pool
		if [[ $? = 0 ]]; then
			$white; echo "P2Pool killed"
		else
			print_Error "P2Pool was not killed"
		fi
	}
	p2pool_stop_Template
}

p2pool_Full()
{
	COMMANDS(){ "$binP2Pool/p2pool" --host "$DAEMON_IP" --wallet "$WALLET" --config "$p2poolConf" --loglevel 2;}
	p2pool_start_Template
}
