#!/usr/bin/env bash
#
# Path Functions
#
# manages path installation, removal, etc.
#
path_Add()
{
	if [[ -f "/usr/local/bin/monero-bash" ]]; then
		$ired; echo "monero-bash PATH is already set: "
		$white; echo "/usr/local/bin/monero-bash"
	else
		sudo ln -s "$installDirectory/monero-bash" "/usr/local/bin/monero-bash"
		error_Continue "Adding to PATH failed"
	fi
}

path_Remove()
{
	if [[ -f "/usr/local/bin/monero-bash" ]]; then
		sudo rm "/usr/local/bin/monero-bash"
	else
		$ired; echo "monero-bash PATH is not set"
	fi
}

path_Reset()
{
	echo "Resetting monero-bash PATH..."
	sudo rm "/usr/local/bin/monero-bash"
	error_Exit "Removing from PATH failed"
	sudo ln -s "$installDirectory/monero-bash" "/usr/local/bin/monero-bash"
	error_Exit "Adding to PATH failed"
	$igreen; echo "monero-bash PATH reset!"
}
