#!/usr/bin/env bash
#
#                       Print Functions
#
print_GreenHash()
{
	$igreen; echo "###### $1" ;$off
}

print_RedHash()
{
	$ired; echo "###### $1" ;$off
}

print_MoneroBashTitle()
{
	$bred; echo "###################"
	$bred; echo "#   monero-bash   #"
	$bred; echo "###################"
	$off
}

print_Version()
{
	$white; echo -n "Monero-CLI: "
	if [[ $MONERO_CLI_OLD = "false" ]]; then
		$bgreen; echo "$MONERO_CLI_VER"
	else
		$bred; echo "$MONERO_CLI_VER"
	fi
		$white; echo -n "monero-bash: "
	if [[ $MONERO_BASH_OLD = "false" ]]; then
		$bgreen; echo "$MONERO_BASH_VER"
	else
		$bred; echo "$MONERO_BASH_VER"
	fi
}

print_Usage()
{
    $off; echo -n "monero-bash usage: "
    $ired; echo "monero-bash <option> <more options>" ;$off
    echo
    cat "$installDirectory/src/usage"
    echo
    $ired; echo -n "monero-bash, "
    $white; echo -n "made by: "
    $bgreen; echo "hinto.janaiyo"
}

print_Size()
{
	$white; echo -n "monero-bash install: " ;$ired
	du -h "$installDirectory" | tail -n 1 | awk '{print $1}'
	$white; echo -n "$MoneroBashFolder: " ;$ired
	du -h "$MoneroBashFolder" | tail -n 1 | awk '{print $1}'
}


print_SeedLanguageList()
{
cat <<EOM
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
11 : Lojban
EOM
}
