#!/usr/bin/env bash
# for interacting with monerod/p2pool/xmrig

process_Start_Template()
{
	prompt_Sudo;error_Sudo

	# CHECK IF MISSING BINARY
	missing_"$NAME_FUNC"

	# CONFIGURE P2POOL (only once)
	[[ "$MINE_UNCONFIGURED" = "true" && $PROCESS = "p2pool" ]]&& mine_Config

	# START PROCESS IF NOT ALREADY ALIVE
	if pgrep $PROCESS &>/dev/null ; then
        $bred; echo "$PROCESS already detected..." ;$off
    else
		missing_config_"$NAME_FUNC"
		$bblue; echo "Starting $PROCESS..." ;$off
		COMMANDS
		error_Exit "Could not start $PROCESS"
	fi
}

process_Stop_Template()
{
	if pgrep $PROCESS &>/dev/null ; then
		COMMANDS
	else
		$white; echo -n "$PROCESS: "
		$bred; echo "not online" ;$off
	fi
}

process_Restart()
{
	process_Stop
	process_Start
}

process_Start()
{
	COMMANDS()
	{
		missing_systemd_"$NAME_FUNC"
		sudo systemctl start "$SERVICE"
	}
	process_Start_Template
}

process_Stop()
{
	COMMANDS()
	{
		$ired; echo "Stopping $PROCESS gracefully..." ;$off
		sudo systemctl stop "$SERVICE" &
		for i in {1..30} ;do
			if [[ "$i" = "30" ]]; then
				echo
				print_Error "$PROCESS not responding, killing..."
				process_Kill
			fi
			if pgrep $PROCESS &>/dev/null ;then
				echo -n "."
			else
				echo "."
				break
			fi
			sleep 1
		done
	}
	process_Stop_Template
}

process_Kill()
{
	prompt_Sudo;error_Sudo
	COMMANDS()
	{
		$ired; echo "Killing $PROCESS..."
		sudo systemctl kill "$SERVICE"
		if [[ $? = 0 ]]; then
			$white; echo "$PROCESS killed"
		else
			print_Error "$PROCESS was not killed"
		fi
	}
	process_Stop_Template
}

process_Full()
{
	case $PROCESS in
		monerod) COMMANDS(){ "$binMonero/monerod" --config-file "$config/monerod.conf" ;} ;;
		p2pool) COMMANDS(){ "$binP2Pool/p2pool" \
			--config $p2poolConf --host "$DAEMON_IP" --wallet "$WALLET" --config "$p2poolConf" --loglevel "$LOG_LEVEL" "$EXTRA_FLAGS";} ;;
		xmrig) COMMANDS(){ sudo $binXMRig/xmrig --config $xmrigConf ;} ;;
	esac
	process_Start_Template
}
