#!/usr/bin/env bash
# for interacting with monerod/p2pool/xmrig

process_Start_Template()
{
	# SUDO NOT NEEDED FOR MONEROD
	if [[ $NAME_PRETTY != "Monero" ]]; then
		prompt_Sudo;error_Sudo
	fi

	# CHECK IF MISSING BINARY
	missing_"$NAME_FUNC"

	# CONFIGURE P2POOL (only once)
	if [[ "$MINE_UNCONFIGURED" = "true" && $PROCESS = "p2pool" ]]; then
		mine_Config
		exit
	fi

	# START PROCESS IF NOT ALREADY ALIVE
	if pgrep $PROCESS &>/dev/null ; then
        $bred; echo "$PROCESS already detected..." ;$off
    else
		missing_config_"$NAME_FUNC"

		# REFRESH LOGS
		if [[ $NAME_PRETTY = "P2Pool" ]]; then
			[[ -e "$binP2Pool/p2pool.log" ]]&& sudo rm "$binP2Pool/p2pool.log"
		elif [[ $NAME_PRETTY = "XMRig" && -e "$binXMRig/xmrig-log" ]]; then
			sudo rm "$binXMRig/xmrig-log"
			sudo touch "$binXMRig/xmrig-log"
			sudo chown "$USER:$USER" "$binXMRig/xmrig-log"
		fi

		# START PROCESS
		$bblue; echo "Starting $PROCESS..." ;$off
		COMMANDS
		error_Exit "Could not start $PROCESS"
	fi
}

process_Stop_Template()
{
	prompt_Sudo;error_Sudo
	if pgrep $PROCESS &>/dev/null ; then
		COMMANDS
	else
		$white; echo -n "$PROCESS: "
		$bred; echo "not online" ;$off
	fi
}

process_Restart()
{
	process_Stop
	process_Start
}

process_Start()
{
	COMMANDS()
	{
		missing_systemd_"$NAME_FUNC"
		sudo systemctl start "$SERVICE"
	}
	process_Start_Template
}

process_Stop()
{
	COMMANDS()
	{
		$ired; echo "Stopping $PROCESS gracefully..." ;$off
		sudo systemctl stop "$SERVICE" &
		for i in {1..30} ;do
			if [[ "$i" = "30" ]]; then
				echo
				print_Error "$PROCESS not responding, killing..."
				process_Kill
			fi
			if pgrep $PROCESS &>/dev/null ;then
				echo -n "."
			else
				echo "."
				break
			fi
			sleep 1
		done
	}
	process_Stop_Template
}

process_Kill()
{
	prompt_Sudo;error_Sudo
	COMMANDS()
	{
		$ired; echo "Sending kill signal to $PROCESS..."
		sudo systemctl kill "$SERVICE"
	}
	process_Stop_Template
}

process_Full()
{
	case $PROCESS in
		monerod) COMMANDS(){ cd "$binMonero" ; "$binMonero/monerod" --config-file "$config/monerod.conf" ;} ;;
		p2pool) COMMANDS(){ cd "$binP2Pool" ; "$binP2Pool/p2pool" --config $p2poolConf --host "$DAEMON_IP" --wallet "$WALLET" --loglevel "$LOG_LEVEL" ;} ;;
		xmrig) COMMANDS(){ cd "$binXMRig" ; sudo "$binXMRig/xmrig" --config "$xmrigConf" --log-file="$binXMRig/xmrig-log" ;} ;;
	esac
	process_Start_Template
}
