#!/usr/bin/env bash
#
#						Prompt Functions
#
prompt_YESno()
{
	read yn
	if [[ $yn = "" || $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	else
		No
	fi
}

prompt_NOyes()
{
	read yn
	if [[ $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	elif [[ $yn = "" ]]; then
		No
	else
		No
	fi
}

prompt_Sudo()
{
	sudo echo -n
}

prompt_PriceAPI_IP()
{
	if [[ $PRICE_API_IP_WARNING = "true" ]]; then
		$white; echo -n "Edit "
		$ired; echo -n "PRICE_API_IP_WARNING "
		$white; echo -n "in "
		$ired; echo -n "monero-bash.conf "
		$white; echo "to silence this warning"
		echo
		$white; echo -n "This will expose your IP to: "
		$ired; echo "https://cryptocompare.com"
		$white; echo -n "Continue? (y/N) "
		Yes(){ :;}
		No(){ echo "Exiting..." ;exit 1;}
		prompt_NOyes
	fi
}
