#!/usr/bin/env bash
# remove functions
remove_Template()
{
	if [[ "$NAME_VER" = "" && "$FORCE_REMOVE" != "true" ]]; then
		$white; echo -n "$NAME_PRETTY: "
		$ired; echo "is not installed"
	else
		prompt_Sudo;error_Sudo
		echo;safety_HashList
		trap "trap_No" 1 2 3 6 15
		print_RedHash "Removing [$NAME_PRETTY]"
		sudo rm -rf "$DIRECTORY"
		sudo rm "$sysd/monero-bash-$name"
		print_WhiteHash "Updating local state"
		sudo sed -i "s@.*"$NAME_CAPS"_VER=.*@"$NAME_CAPS"_VER=\"\"@" "$state"
		sudo sed -i "s@.*"$NAME_CAPS"_OLD=.*@"$NAME_CAPS"_OLD=\"true\"@" "$state"
		PRODUCE_HASH_LIST
		print_RedHash "Removed [$NAME_PRETTY]"
	fi
}

remove_Monero()
{
	define_Monero
	local name="monerod"
	remove_Template
}

remove_MoneroBash()
{
	$iwhite; echo -n "type: "
	$bred; echo -n "monero-bash uninstall "
	$iwhite; echo "to remove monero-bash"
}

remove_XMRig()
{
	define_XMRig
	local name="xmrig"
	remove_Template
}

remove_P2Pool()
{
	define_P2Pool
	local name="p2pool"
	remove_Template
}

remove_All()
{
	remove_Monero
	remove_XMRig
	remove_P2Pool
}
