#!/usr/bin/env bash
#
# Safety checks so monero-bash doesn't blow something up

# checks if /.monero-bash/ exists, if not, build default
safety_DotMoneroBash()
{
    if [[ ! -d "$dotMoneroBash" ]]; then
        print_Error "$HOME/.monero-bash/ folder not found!"
        $white; printf "Build a default folder? (Y/n) "
		Yes(){ build_DotMoneroBash ;}
		No(){ echo "Exiting..." ;exit;}
		prompt_YESno
    fi
}
# checks if the home folder exists
safety_Home()
{
	if [[ ! -d "$HOME" ]]; then
		$ired; echo "monero bash error: User's home folder does not exist!"
		echo "Exiting..."
		exit
	fi
}

# checks if the basic linux folders exists at all
safety_LinuxFolders()
{
	if [[ ! -d "/usr/local/share/" || ! -d "/usr/local/bin/" ]]; then
		$ired; echo "/usr/ folder error!"
		$white; echo "monero-bash needs a normal /usr/ folder"
		echo "Exiting..."
		exit
	fi
}

# check if in /usr/local/share/monero-bash
safety_UsrLocalShare()
{
	if [[ "$installDirectory" != "/usr/local/share/monero-bash" ]]; then
		$ired; echo "error: monero-bash not in /usr/local/share/ !"
		$white; echo "was monero-bash installed properly?"
		echo "Exiting for safety..."
		exit
	fi
}

# checks quiet_hashlist only if not previously checked (used in download)
safety_HashList()
{
	if [[ $alreadyCheckedHashList != "true" ]]; then
		QUIET_HASH_LIST
		alreadyCheckedHashList="true"
		echo
	fi
}

safety_Root()
{
	if [[ "$EUID" = 0 ]]; then
		printf "\033[1;31mMONERO-BASH ERROR: "
		printf "\033[1;37mDO NOT RUN AS ROOT\n"
		exit
	fi
}

# checks if basic linux dependencies are installed
safety_Deps()
{
	if [[ ! -e "/usr/bin/systemctl" ]]; then
		print_Error_Exit "/usr/bin/systemctl (systemd) not found!"
	elif [[ ! -e "$sysd" ]]; then
		print_Error_Exit "$sysd not found!"
	elif [[ ! -e "/usr/bin/gpg" ]]; then
		print_Error_Exit "/usr/bin/gpg (GPG) not found!"
	elif [[ ! -e "/usr/bin/wget" ]]; then
		print_Error_Exit "/usr/bin/gpg (wget) not found!"
	elif [[ ! -e "/usr/bin/sed" || ! -e "/usr/bin/awk" || ! -e "/usr/bin/grep" || ! -e "/usr/bin/tail" || ! -e "/usr/bin/head" ]]; then
		print_Error_Exit "Basic GNU tools not found!"
	fi
}

# monero-bash only supports 1 user
safety_User()
{
	if [[ "$INSTALLED_USER" != "$USER" ]]; then
		printf "\033[1;31mmonero-bash error: "
		printf "\033[0mOnly this user is allowed: "
		printf "\033[1;37m$INSTALLED_USER\n"
		exit
	fi
}
