#!/usr/bin/env bash
# status function, prints multiple helpful stats

status_All()
{
	print_MoneroBashTitle
	wallet_Count
	wallet_List
	if [[ $ZERO_WALLETS != "true" ]]; then
		echo
	fi
	print_Version
	echo
	status_Monero
	status_P2Pool
	status_XMRig
}

status_Template()
{
	$bwhite; echo -n "$NAME_PRETTY: " ;$off
	if pgrep $PROCESS &>/dev/null ;then
		$bgreen; echo "online" ;$off
		EXTRA_STATS
	else
		$bred; echo "offline" ;$off
	fi
}

status_Monero()
{
	define_Monero
	EXTRA_STATS(){ $binMonero/monerod status ;}
	status_Template
}

status_P2Pool()
{
	define_P2Pool
	EXTRA_STATS(){ journalctl -u monero-bash-p2pool --output cat | tail -n4 ;}
	status_Template
}

status_XMRig()
{
	define_XMRig
	EXTRA_STATS(){ journalctl -u monero-bash-xmrig --output cat | tail -n4 ;}
	status_Template
}
