#!/usr/bin/env bash
# status function, prints multiple helpful stats

status_All()
{
	prompt_Sudo;error_Sudo
	print_MoneroBashTitle
	wallet_Count
	wallet_List
	print_Version
	echo
	[[ $MONERO_VER != "" ]]&& status_Monero
	[[ $P2POOL_VER != "" ]]&& status_P2Pool
	[[ $XMRIG_VER != "" ]]&& status_XMRig
}

status_Template()
{
	$bwhite; echo -n "$NAME_PRETTY: " ;$off
	if pgrep $PROCESS &>/dev/null ;then
		$bgreen; echo "online" ;$off
		EXTRA_STATS
	else
		$bred; echo "offline" ;$off
	fi
}

status_Monero()
{
	define_Monero
	EXTRA_STATS(){ $binMonero/monerod status ;echo;}
	status_Template
}

status_P2Pool()
{
	define_P2Pool
	EXTRA_STATS()
	{
		$bwhite; echo -n "Wallet: "
		$white; echo "$WALLET"
		journalctl -u "$SERVICE" --output cat | tail -n4
		echo
	}
	status_Template
}

status_XMRig()
{
	define_XMRig
	EXTRA_STATS()
	{
		$bwhite; echo -n "Wallet: " ;$off
		grep "\"user\":" "$xmrigConf" | awk '{print $2}' | tr -d '","'
		$bwhite; echo -n "Pool: " ;$off
		grep "\"url\":" "$xmrigConf" | awk '{print $2}' | tr -d '","'
		sudo journalctl -u "$SERVICE" --output cat | tail -n4
	}
	status_Template
}
