#!/usr/bin/env bash
# functions for creating /tmp/ folders

tmp_Create()
{
	tmp_Del
	mktemp -d /tmp/monero-bash.XXXXXXXXXX &>/dev/null
}

tmp_Del()
{
	if find /tmp/monero-bash.* &>/dev/null ; then
		rm -rf /tmp/monero-bash.*
	fi
}
