#!/usr/bin/env bash
# trap that handles exits (and cleanup)
trap_Template()
{
	trap "" 1 2 3 6 15
	[[ $VERBOSE = "true" ]]&& verbose_Upgrade
}

# continue current operation until finished and revert (ONLY FOR UPGRADE)
trap_No()
{
	trap_Template
	trapSet="true"
	error_Trap "LETTING DATA TRANSFER FINISH TO PREVENT CORRUPTION"
	exit
}

# does everything POST install (rm temp files, state, hash)
trap_Post()
{
	trap_Template
	error_Trap "WRITING TO STATE BEFORE EXITING"
	version_Template
	sudo -u "$USER" sed -i "s@.*"$NAME_CAPS"_VER=.*@"$NAME_CAPS"_VER=\""$NewVer"\"@" "$state"
	sudo -u "$USER" sed -i "s@.*"$NAME_CAPS"_OLD=.*@"$NAME_CAPS"_OLD=\"false\"@" "$state"
	[[ "$INSTALL" = "true" ]]&& systemd_"$NAME_FUNC"
	PRODUCE_HASH_LIST
	sudo chown -R $USER "$installDirectory"
	[[ -d "$old" ]]&& sudo rm -rf "$old"
	tmp_Del
	exit
}

# delete tmp folder
trap_Tmp()
{
	trap_Template
	error_Trap "CLEANING TEMP FILES"
	tmp_Del
	exit
}

# revert monero-bash upgrades
trap_MoneroBash()
{
	trap_Template
	error_Trap "RESTORING OLD MONERO-BASH"
	sudo -u "$USER" mv -f "$old/monero-bash" "$installDirectory"
	sudo -u "$USER" mv -fr "$old/src" "$installDirectory"
	sudo -u "$USER" mv -fr "$old/config" "$installDirectory"
	sudo -u "$USER" mv -fr "$old/gpg" "$installDirectory"
	sudo -u "$USER" mv -f "$old/src/txt/state" "$state"
	tmp_Del
	exit
}

# delete old folder
trap_Old()
{
	trap_Template
	error_Trap "CLEANING OLD FOLDER"
	[[ -d "$old" ]]&& rm -rf "$old"
	tmp_Del
	exit
}

# revert gpg toggle
trap_GPG()
{
	trap_Template
	error_Trap "REVERTING GPG TOGGLE"
	sudo -u "$USER" sed -i "s@.*VERIFY_GPG=.*@VERIFY_GPG=\"false\"@" "$state"
	PRODUCE_HASH_LIST
	exit
}

# recreate hash list
trap_Hash()
{
	trap_Template
	error_Trap "RE-PRODUCING HASHLIST"
	PRODUCE_HASH_LIST
	exit
}
