#!/usr/bin/env bash
# update functions

update_Template()
{
	prompt_Sudo
	error_Sudo
	version_"$NAME_FUNC"
	if [[ "$NAME_VER" != "$NewVer" ]]; then
		$white; echo -n "$NAME_PRETTY: "
		$ired; echo -n "$NAME_VER "
		$white; echo -n "> "
		$bgreen; echo "$NAME_NEWVER"
		updateFound="true"
		sudo sed -i "s@.*"$NAME_OLD"=.*@"$NAME_OLD"=\"true\"@" "$state"
		PRODUCE_HASH_LIST &>/dev/null
	else
		sudo sed -i "s@.*"$NAME_OLD"=.*@"$NAME_OLD"=\"false\"@" "$state"
		$white; echo -n "$NAME_PRETTY: "
		$bgreen; echo "up to date"
	fi
}

update_Monero()
{
	NAME_FUNC="NewMonero"
	NAME_PRETTY="Monero"
	NAME_VER="$MONERO_VER"
	NAME_OLD="MONERO_OLD"
	update_Template
}

update_MoneroBash()
{
	NAME_FUNC="NewMoneroBash"
	NAME_PRETTY="monero-bash"
	NAME_VER="$MONERO_BASH_VER"
	NAME_OLD="MONERO_BASH_OLD"
	update_Template
}

update_XMRig()
{
	NAME_FUNC="NewXMRig"
	NAME_PRETTY="XMRig"
	NAME_VER="$XMRIG_VER"
	NAME_OLD="XMRIG_OLD"
	update_Template
}

update_P2Pool()
{
	NAME_FUNC="NewP2Pool"
	NAME_PRETTY="P2Pool"
	NAME_VER="$P2POOL_VER"
	NAME_OLD="P2POOL_OLD"
	update_Template
}

update_All()
{
	update_MoneroBash
	[[ $MONERO_VER != "" ]]&& update_Monero
	[[ $XMRIG_VER != "" ]]&& update_XMRig
	[[ $P2POOL_VER != "" ]]&& update_P2Pool
    if [[ $updateFound = "true" ]]; then
        echo
        $ired; echo -n "monero-bash upgrade "
        $white; echo "to upgrade all"
        $white; echo -n "or: "
        $ired; echo -n "monero-bash upgrade <name> "
        $white; echo "to upgrade something specific"
        $off
    fi
}
