#!/usr/bin/env bash
# update functions

update_Template()
{
	version_Update
	if [[ "$NAME_VER" != "$NewVer" ]]; then
		$bwhite; echo -n "$NAME_PRETTY: "
		$bred; echo -n "$NAME_VER "
		$bwhite; echo -n "> "
		$bgreen; echo "$NewVer"
		updateFound="true"
		sudo sed -i "s@.*"$NAME_CAPS"_OLD=.*@"$NAME_CAPS"_OLD=\"true\"@" "$state"
		PRODUCE_HASH_LIST &>/dev/null
	else
		sudo sed -i "s@.*"$NAME_CAPS"_OLD=.*@"$NAME_CAPS"_OLD=\"false\"@" "$state"
		PRODUCE_HASH_LIST &>/dev/null
		$bwhite; echo -n "$NAME_PRETTY: "
		$bgreen; echo "$NAME_VER"
	fi
}

update_Monero()
{
	define_Monero
	update_Template
}

update_MoneroBash()
{
	define_MoneroBash
	update_Template
}

update_XMRig()
{
	define_XMRig
	update_Template
}

update_P2Pool()
{
	define_P2Pool
	update_Template
}

update_All()
{
	prompt_Sudo
	error_Sudo
	$bwhite; echo "Checking for updates..."
	update_MoneroBash
	[[ $MONERO_VER != "" ]]&& update_Monero
	[[ $XMRIG_VER != "" ]]&& update_XMRig
	[[ $P2POOL_VER != "" ]]&& update_P2Pool
    if [[ $updateFound = "true" ]]; then
        echo
        $ired; echo -n "monero-bash upgrade "
        $white; echo "to upgrade all"
        $white; echo -n "or: "
        $ired; echo -n "monero-bash upgrade <package> "
        $white; echo "to upgrade something specific"
        $off
    fi
}
