#!/bin/bash
#
#
#
#upgrade_MoneroBash
upgrade_Monero()
{
	prompt_Sudo
	cleanup_Tmp
	print_GreenHash "Downloading: [Monero]"
	download_Monero
	error_Exit "Downloading failed: [Monero]"
	verify_Monero
	if [[ $? = "0" ]]; then
        print_RedHash "Extracting: [Monero]"
        tar -xf $monero_tar
        rm -f $monero_tar
        version_Variables
        sudo sed -i "s@.*MONERO_VER=.*@MONERO_VER=\""$monero_NewVer"\"@" "$state"
        monero_fol="$(ls | grep "monero-x86_64-linux-gnu")"
		rm -rf "$binMonero"
		mkdir -p "$binMonero"
		mv "$monero_fol/" "$binMonero"
		sudo sed -i "s@.*MONERO_OLD=.*@MONERO_OLD=\"false\"@" "$state"
    else
		compromised_Monero_Hash
        exit
    fi
	cleanup_Tmp
}
#upgrade_All
