#!/usr/bin/env bash
#
# Monero Wallet Functions

wallet_Start()
{
	# CHECK IF MISSING BINARY
	missing_MoneroCLI

	# AUTO MONEROD START
	[[ $AUTO_START_DAEMON = "true" ]]&& define_Monero&&process_Start

	# CD INTO .monero-bash SO FILES/LOGS GET CREATED THERE
	cd "$dotMoneroBash"

	# NORMAL WALLET CREATION
	if [[ $createWallet = "true" ]]; then
		"$binMonero/monero-wallet-cli" \
			--generate-new-wallet "$wallets/$walletName" \
			--password "$walletPassword" \
			--mnemonic-language "$seedLanguage" \
			--config-file "$config/monero-wallet-cli.conf"
			error_Exit "Could not start monero-wallet-cli"

	# VIEW WALLET CREATION
	elif [[ $createView = "true" ]]; then
		"$binMonero/monero-wallet-cli" \
			--generate-from-view-key "$wallets/$walletName" \
			--password "$walletPassword" \
			--config-file "$config/monero-wallet-cli.conf"
			error_Exit "Could not start monero-wallet-cli"

	# WALLET RECOVERY WITH STANDARD SEED
	elif [[ $recoverWallet = "true" ]]; then
		"$binMonero/monero-wallet-cli" \
			--generate-new-wallet "$wallets/$walletName" \
			--password "$walletPassword" \
			--restore-from-seed \
			--electrum-seed "$walletSeed" \
			--config-file "$config/monero-wallet-cli.conf"
			error_Exit "Could not start monero-wallet-cli"
	else

	# IF NOT CREATING, START NORMALLY
		"$binMonero/monero-wallet-cli" \
			--wallet-file "$wallets/$walletSelection" \
			--password "$walletPassword" \
			--config-file "$config/monero-wallet-cli.conf"
			error_Exit "Could not start monero-wallet-cli"
	fi

	# AUTO MONEROD STOP
	[[ $AUTO_STOP_DAEMON = "true" ]]&& define_Monero&&process_Stop
	exit 0
}

wallet_Template()
{
	# WALLET NAME
	while true ;do
		$white; echo -n "New wallet name: " ;$iwhite
		read walletName
		if [[ "$walletName" = *" "* || "$walletName" = "" ]]; then
			print_Error "wallet name cannot be empty or have spaces"
		else
			break
		fi
	done

	# WALLET PASS
	while true; do
		$white; echo -n "Wallet password: "
		read -s walletPassword
		echo
		$white; echo -n "Enter password again: "
		read -s walletPasswordAgain
		echo
		if [[ "$walletPassword" = "$walletPasswordAgain" ]]; then
			break
		else
			print_Error "Password was not the same!"
		fi
	done
}
wallet_Create()
{
	wallet_Template

	# WALLET SEED LANGUAGE
	while true ;do
		$ired; echo "Monero seed languages:" ;$iwhite
		print_SeedLanguageList
		$white; echo -n "Pick seed language: " ;$iwhite
		read seedLanguage
			case "$seedLanguage" in
				"0"|deutsch|Deutsch|german|German) seedLanguage="Deutsch" ;break ;;
				"1"|english|English) seedLanguage="English" ;break ;;
				"2"|español|Español|spanish|Spanish) seedLanguage="Español" ;break ;;
				"3"|français|Français|french|French) seedLanguage="Français" ;break ;;
				"4"|italiano|Italiano|italian|Italian) seedLanguage="Italiano" ;break ;;
				"5"|nederlands|Nederlands|dutch|Dutch) seedLanguage="Nederlands" ;break ;;
				"6"|português|Português|portuguese|Portuguese) seedLanguage="Português" ;break ;;
				"7"|"русский язык"|russian|Russian) seedLanguage="русский язык" ;break ;;
				"8"|日本語|にほんご|japanese|Japanese) seedLanguage="日本語" ;break ;;
				"9"|"简体中文(中国)"|"简体中文"|"简体中文 (中国)"|chinese|Chinese) seedLanguage="简体中文 (中国)" ;break ;;
				"10"|esperanto|Esperanto) seedLanguage="Esperanto" ;break ;;
				"11"|lojban|Lojban) seedLanguage="Lojban" ;break ;;
				*) print_Error "invalid input" ;;
			esac
		done

	# START monero-wallet-cli WITH CREATION VARIABLES SET
	$bred; echo "Starting Monero..." ;$off
	createWallet="true"
	wallet_Start
}

# creation of view-only wallet
wallet_View()
{
	$bred; echo "Creating [view] wallet..." ;$off
	wallet_Template

	# START monero-wallet-cli WITH CREATION VARIABLES SET
	$bred; echo "Starting Monero..." ;$off
	createView="true"
	wallet_Start
}

# recovery of wallet
wallet_Recover()
{
	$bred; echo "Recovering wallet..." ;$off
	wallet_Template

	# SEED INPUT
	while true ;do
		$white; echo -n "Seed: "
		read -s walletSeed ; echo
		case $walletSeed in
			"") print_Error "Empty input" ;;
			*) break ;;
		esac
	done

	# START monero-wallet-cli WITH RECOVERY VARIABLES SET
	$bred; echo "Starting Monero..." ;$off
	recoverWallet="true"
	wallet_Start
}

# if wallet name happens to be "new/view/recover"
wallet_Collision()
{
	$white; echo "Wallet name is similar to option..."
	while true ;do
	$iblue; printf "SELECT "
	$white; printf "or "
	$ired; printf "CREATE? " ;$off
	read selectCreate
		case $selectCreate in
			select|Select|SELECT)
				$off; echo "Selecting $walletSelection..."
				echo -n "Password: "
				read -s walletPassword && echo
				wallet_Start
				exit
				;;
			create|Create|CREATE)
				break
				;;
			*) print_Error "Invalid option" ;;
		esac
	done
}

wallet_Count()
{
	walletCount="$(ls "$wallets" | grep -v ".keys" | wc -l)"
	$bwhite; echo -n "$walletCount " ;$off
	if [[ $walletCount = "1" ]]; then
		echo "wallet found:"
	elif [[ $walletCount > "1" ]]; then
		echo "wallets found: "
	elif [[ $walletCount = "0" ]]; then
		echo "wallets found"
	fi
}

wallet_List()
{
	walletList=($(ls "$wallets" | grep -v ".keys"))
	wallet_list_pretty()
	{
		for i in ${walletList[*]}; do
			printf "[${i}]  "
		done
	}
	# print nice spacing regardless if wallets exist or not
	if [[ $walletList = "" ]]; then
		echo
	else
		$bwhite; echo "$(wallet_list_pretty)"
		echo
	fi
}
