#!/usr/bin/env bash
#
# watch functions - for watching output of the systemd services created
# by monero-bash, e.g. "monero-bash-xmrig.service"
#
# this function would be much simpler to implement if i could use "screen".
# although that program is GNU, it is not within the coreutils, and also not
# pre-installed on Arch, Debian, Fedora, etc.
#
# and so, this is a (poor man's) version using tools most Linux distros have
# (bash + coreutils + procps + journalctl/systemd)

watch_Template()
{
	while true ;do
		trap "break" INT
		watch -t -c "journalctl -u monero-bash-$NAME --output cat | tail -n $(tput lines)"
		sleep 1
	done
}

watch_Monerod()
{
	local NAME="monerod"
	watch_Template
}

watch_XMRig()
{
	local NAME="xmrig"
	watch_Template
}

watch_P2Pool()
{
	local NAME="p2pool"
	watch_Template
}
