#!/usr/bin/env bash
#
# watch functions - for watching output of the systemd services created
# by monero-bash, e.g. "monero-bash-xmrig.service"
#
# this function would be much simpler to implement if i could use "screen".
# although that program is GNU, it is not within the coreutils, and also not
# pre-installed on Arch, Debian, Fedora, etc.
#
# and so, this is a (poor man's) version using tools most Linux distros have

watch_Template()
{
	# tput lines = available lines detected terminal
	# divided by 2 to account for line wraps.
	# 1 line that line wraps still counts as 1 line,
	# this makes it so bottom messages won't be seen.
	local LINES=$(($(tput lines) / 2))
	if [[ "$SERVICE" = "monero-bash-xmrig.service" ]]; then
		sudo watch -n 1 -t -c "journalctl -u $SERVICE --output cat | tail -n $LINES"
	else
		watch -n 1 -t -c "journalctl -u $SERVICE --output cat | tail -n $LINES"
	fi
}

watch_Monero()
{
	define_Monero
	watch_Template
}

watch_XMRig()
{
	define_XMRig
	watch_Template
}

watch_P2Pool()
{
	define_P2Pool
	watch_Template
}
