#!/usr/bin/env bash
#
# xmrig functions for systemd/non-systemd

xmrig_Start()
{
	sudo $binXMRig/xmrig --config $config/xmrig.json
}

xmrig_systemd_Start()
{
	sudo systemctl start monero-bash-xmrig
}
