#!/usr/bin/env bash

# installDirectory = where ever /monero-bash/ is
scriptPath="$(realpath $0)"
installDirectory="$(dirname "$scriptPath")"

# check if script is in monero-bash folder
if [[ $installDirectory != *"/monero-bash" ]]; then
	printf "\033[1;31mExecuting monero-bash while it isn't in the /monero-bash/ folder is DANGEROUS\n"
	printf "\033[0;31mExiting for safety...\n"
	exit
fi

# source files, exit on failure
cd "$installDirectory"
source "$installDirectory/src/source"
[[ $? != "0" ]]&& printf "\033[1;31mMONERO BASH: SOURCING ERROR\n" && exit
case true in
	$varMissing) printf "\033[1;31mMONERO BASH: Variables not sourced\n" ;exit;;
	$funcMissing) printf "\033[1;31mMONERO BASH: Functions not sourced\n" ;exit;;
	$stateMissing) printf "\033[1;31mMONERO BASH: state file missing\n" ;exit;;
	$debugMissing) printf "\033[1;31mMONERO BASH: debug file missing\n" ;exit;;
	$hashlistMissing) printf "\033[1;31mMONERO BASH: hashlist file missing\n" ;exit;;
esac

# DEBUG COMMAND - read /src/debug for more info
if [[ $1 = "DEBUG_04e3be9" ]]; then
	case $2 in
		"") DEBUG_04e3be9 ;;
		*) "$2" ;;
	esac
	exit
fi

# safety checks
safety_Root
safety_Deps
safety_LinuxFolders
safety_Home

# Installation
if [[ $FIRST_TIME = "true" ]]; then
	monerobash_Install
	exit
fi

# even more safety checks
if [[ $FIRST_TIME != "true" ]]; then
	safety_UsrLocalShare
	safety_User
	safety_DotMoneroBash
	missing_Wallets
	missing_config_Folder
	missing_config_All
	missing_systemd_All
fi

# interactive/option check
[[ $1 = "" ]]&& interactive="true"
[[ $1 != "" ]]&& options="true"

# Interactive Wallet Selection
if [[ $interactive = "true" ]]; then
	print_MoneroBashTitle
	if [[ $AUTO_UPDATE = "true" ]]; then
		update_All
		echo
	fi

	# SHOW WALLETS, SELECT
	$white; wallet_Count ; wallet_List ; echo
	while true ;do
		$white; echo -n "Pick "
		$iblue; echo -n "wallet "
		$white; echo "or "
		$ired; echo -n "[new / view / recover]"
		$white; echo -n ": "
		read walletSelection

		# IF WALLET NAME COLLIDES WITH OPTION, ASK FOR CLARIFICATION
		if [[ $walletList = *"$walletSelection"* && $walletSelection = "new" \
			|| $walletList = *"$walletSelection"* && $walletSelection = "view" \
			|| $walletList = *"$walletSelection"* && $walletSelection = "recover" ]]; then
			wallet_Collision

		# ELSE, START WALLET NORMALLY
		elif [[ $walletList = *"$walletSelection"* ]]; then
			$white; echo -n "Password: "
			read -s walletPassword && echo
			wallet_Start
			break
		elif [[ $walletSelection = "" ]]; then
			print_Error "empty input"
		fi

		# WALLET CREATION
		case $walletSelection in
			new|New|NEW|"[new]"|"[New]") wallet_Create ; break ;;
			view|View|VIEW|view-only|View-only|View-Only) wallet_View ; break ;;
			recover|Recover|RECOVER|"[recover]"|"[Recover]") wallet_Recover ; break ;;
			*) $ired; print_Error "wallet does not exist" ;;
		esac
	done
	exit
fi

# Option Flags
if [[ $options = "true" ]]; then
	case $1 in
		backup) backup_Wallets ;;
		decrypt) backup_Decrypt ;;
		uninstall) monerobash_Uninstall ;;
		update) update_All ;;
		version) print_Version ;;
		list) wallet_Count && wallet_List ;;
		size) print_Size ;;
		price) check_Price ;;
		status) status_All ;;
		integrity) CHECK_HASH_LIST ;;
		help) print_Usage ;;
		config) mine_Config ;;
		edit)
			case $2 in
				daemon) define_Monero;systemd_Edit ;;
				xmrig) define_XMRig;systemd_Edit ;;
				p2pool) define_P2Pool;systemd_Edit ;;
				*) error_Unknown ;;
			esac
			;;
		start)
			case $2 in
				daemon) define_Monero;process_Start ;;
				xmrig) define_XMRig;process_Start ;;
				p2pool) define_P2Pool;process_Start ;;
				all) mine_Start ;;
				"") print_Error "Pick: <all/daemon/p2pool/xmrig>" ;;
				*) error_Unknown ;;
			esac
			;;
		stop)
			case $2 in
				daemon) define_Monero;process_Stop ;;
				xmrig) define_XMRig;process_Stop ;;
				p2pool) define_P2Pool;process_Stop ;;
				all) mine_Stop ;;
				"") print_Error "Pick: <all/daemon/p2pool/xmrig>" ;;
				*) error_Unknown ;;
			esac
			;;
		restart)
			case $2 in
				daemon) define_Monero;process_Restart ;;
				xmrig) define_XMRig;process_Restart ;;
				p2pool) define_P2Pool;process_Restart ;;
				all) mine_Restart ;;
				"") print_Error "Pick: <all/daemon/p2pool/xmrig>" ;;
				*) error_Unknown ;;
			esac
			;;
		kill)
			case $2 in
				daemon) define_Monero;process_Kill ;;
				xmrig) define_XMRig;process_Kill ;;
				p2pool) define_P2Pool;process_Kill ;;
				all) mine_Kill ;;
				"") print_Error "Pick: <all/daemon/p2pool/xmrig>" ;;
				*) error_Unknown ;;
			esac
			;;
		full)
			case $2 in
				daemon) define_Monero;process_Full ;;
				xmrig) define_XMRig;process_Full ;;
				p2pool) define_P2Pool;process_Full ;;
				"") print_Error "Pick: <daemon/xmrig/p2pool>" ;;
				*) error_Unknown ;;
			esac
			;;
		watch)
			case $2 in
				daemon) watch_Monero ;;
				xmrig) watch_XMRig ;;
				p2pool) watch_P2Pool ;;
				"") print_Error "Pick: <daemon/xmrig/p2pool>" ;;
				*) error_Unknown ;;
			esac
			;;
		gpg)
			case $2 in
				"") gpg_Toggle ;;
				import)
					case $3 in
						all|All|ALL) gpg_import_All ;;
						binaryfate|Binaryfate|monero|Monero|MONERO) gpg_import_Monero ;;
						hinto|hinto-janaiyo|Hinto|monero-bash|Monero-Bash) gpg_import_MoneroBash ;;
						xmrig|XMRig|XMRIG|Xmrig) gpg_import_XMRig ;;
						SChernykh|schernykh|SCHERNYKH|p2pool|p2p|P2P|P2Pool|P2POOL) gpg_import_P2Pool ;;
						*) error_Unknown ;;
					esac
					;;
				*) error_Unknown ;;
			esac
			;;
		upgrade)
			[[ $* = *"verbose"* ]]&& VERBOSE="true"
			[[ $* = *"force"* ]]&& FORCE_UPGRADE="true" &&$ired&& echo "Forcefully upgrading...!" ;$off
			if [[ $2 = *"bash"* || $2 = *"Bash"* || $2 = *"BASH"* ]]; then
				$bwhite; echo -n "Upgrade monero-bash? (Y/n) " ;$off
				Yes(){ upgrade_MoneroBash ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "monero" || $2 = "Monero" || $2 = "MONERO" ]]; then
				$bwhite; echo -n "Upgrade Monero? (Y/n) " ;$off
				Yes(){ upgrade_Monero ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"xmrig"* || $2 = *"XMRig"* || $2 = *"XMRIG"* || $2 = *"Xmrig"* ]]; then
				$bwhite; echo -n "Upgrade XMRig? (Y/n) " ;$off
				Yes(){ upgrade_XMRig ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"p2p"* || $2 = *"P2P"* || $2 = *"P2p"* ]]; then
				$bwhite; echo -n "Upgrade P2Pool? (Y/n) " ;$off
				Yes(){ upgrade_P2Pool ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "all" ]]; then
				$bwhite; echo -n "Upgrade all packages? (Y/n) " ;$off
				Yes(){ upgrade_All ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "" ]]; then
				print_Error "Pick a package or <all>"
				print_Version
			else
				error_Unknown
			fi
			;;
		install)
			[[ $* = *"verbose"* ]]&& VERBOSE="true"
			if [[ $2 = *"bash"* || $2 = *"Bash"* || $2 = *"BASH"* ]]; then
				$bwhite; echo -n "Install monero-bash? (Y/n) " ;$off
				Yes(){ install_MoneroBash ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "monero" || $2 = "Monero" || $2 = "MONERO" ]]; then
				$bwhite; echo -n "Install Monero? (Y/n) " ;$off
				Yes(){ install_Monero ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"xmrig"* || $2 = *"XMRig"* || $2 = *"XMRIG"* || $2 = *"Xmrig"* ]]; then
				$bwhite; echo -n "Install XMRig? (Y/n) " ;$off
				Yes(){ install_XMRig ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"p2p"* || $2 = *"P2P"* || $2 = *"P2p"* ]]; then
				$bwhite; echo -n "Install P2Pool? (Y/n) " ;$off
				Yes(){ install_P2Pool ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "all" ]]; then
				$bwhite; echo -n "Install all packages? (Y/n) " ;$off
				Yes(){ install_All ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "" ]]; then
				print_Error "Pick a package or <all>"
				print_Version
			else
				error_Unknown
			fi
			;;
		remove)
			[[ $* = "force" ]]&& FORCE_REMOVE="true" &&$ired&& echo "Forcefully removing...!" ;$off
			if [[ $2 = *"bash"* || $2 = *"Bash"* || $2 = *"BASH"* ]]; then
				remove_MoneroBash
			elif [[ $2 = "monero" || $2 = "Monero" || $2 = "MONERO" ]]; then
				$bred; echo -n "Remove Monero? (Y/n) " ;$off
				Yes(){ remove_Monero ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"xmrig"* || $2 = *"XMRig"* || $2 = *"XMRIG"* || $2 = *"Xmrig"* ]]; then
				$bred; echo -n "Remove XMRig? (Y/n) " ;$off
				Yes(){ remove_XMRig ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = *"p2p"* || $2 = *"P2P"* || $2 = *"P2p"* ]]; then
				$bred; echo -n "Remove P2Pool? (Y/n) " ;$off
				Yes(){ remove_P2Pool ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "all" ]]; then
				$bred; echo -n "Remove all packages? (Y/n) " ;$off
				Yes(){ remove_All ;}
				No(){ echo "Exiting..." ;exit;}
				prompt_YESno
			elif [[ $2 = "" ]]; then
				print_Error "Pick a package or <all>"
				print_Version
			else
				error_Unknown
			fi
			;;
		*)
			$ired; echo "monero-bash: invalid option!"
			$white; echo -n "for help, type: "
			$bred; echo "monero-bash help"
	esac
	exit
fi
