#!/usr/bin/env bash
# for installing dev branch of monero-bash

[[ -z $1 ]] && echo "specify branch" && exit
BRANCH="$1"

installDirectory="/usr/local/share/monero-bash"
source $installDirectory/src/source || source $installDirectory/src/source.sh

# to bypass the v1.x.x EOL message
NewVer=v1.0.0

upgrade_Template()
{
	$bred; echo "MONERO-BASH DEV INSTALL" ;$off

	cd "$tmp"
	git clone https://github.com/hinto-janaiyo/monero-bash
	cd monero-bash
	git checkout $BRANCH
	NewVer="monero-bash-dev-$(git rev-parse --short HEAD)"

	# TEMP FOLDER FOR OLD PACKAGE
	folderName="$(ls $tmp)"
	if [[ -d "$old" ]]; then
		sudo -u "$USER" rm -rf "$old"
		error_Exit "Could not remove old folder"
	fi

	# SAFETY CHECKS
	[[ "$folderName" = "" || "$tmp" = "" ]]&& echo "EMPTY TMP VARIABLE, EXITING FOR SAFETY" &&exit
	mkdir -p "$old"

	# INSTALL FOR MONERO_BASH
	if [[ "$NAME_CAPS" = "MONERO_BASH" ]]; then
		trap "trap_Old" 1 2 3 6 15
		sudo -u "$USER" cp "$installDirectory/monero-bash" "$old"
		sudo -u "$USER" cp -fr "$installDirectory/src" "$old"
		sudo -u "$USER" cp -fr "$installDirectory/config" "$old"
		sudo -u "$USER" cp -fr "$installDirectory/gpg" "$old"
		trap "trap_MoneroBash" 1 2 3 6 15
		sudo -u "$USER" cp -fr "$tmp/$folderName/monero-bash" "$installDirectory"
		sudo -u "$USER" cp -fr "$tmp/$folderName/src" "$installDirectory"
		sudo -u "$USER" cp -fr "$tmp/$folderName/config" "$installDirectory"
		sudo -u "$USER" cp -fr "$tmp/$folderName/gpg" "$installDirectory"
		sudo -u "$USER" cp -fr "$old/src/txt/state" "$state"
		sudo -u "$USER" cp -fr "$old/src/mini" "$installDirectory/src/"
	fi
	upgrade_Post
}

version_Template()
{
	echo no_ver
}

QUIET_HASH_LIST()
{
	echo no_hash
}

FORCE_UPGRADE="true"
upgrade_MoneroBash
monero-bash DEBUG_04e3be9 PRODUCE_HASH_LIST
