#!/usr/bin/env bash
#
# install all packages and output
# all important variables at the end
#

install()
{
	DEBUG_04e3be9="true"
	printf "\n" | monero-bash install "$1"
}
install monero
install xmrig
install p2p
install bash
