#!/usr/bin/env bash
#
# turns github link into "asdf" which
# forces HTML filter instead of API
#
sed -i 's@api.github.com@asdf@' /usr/local/share/monero-bash/src/func/download
monero-bash DEBUG_04e3be9 PRODUCE_HASH_LIST
readonly HTML="true"
install()
{
	DEBUG_04e3be9="true"
    printf "\n" | monero-bash install "$1"
}
install monero
install xmrig
install p2p
install bash
