#!/usr/bin/env bash
#
# script to create new monero-bash releases
set -e

# git folder
path="$HOME/git/monero-bash"

# copy to tmp
rm -fr "/tmp/monero-bash"
cp -fr "$path" "/tmp/"

# remove non-release files
cd "/tmp/monero-bash"
rm -rf docs .git tests .gitignore LICENSE README.md external lib LICENSE
mv -f CHANGELOG.md /tmp/CHANGELOG.md

# version
source "$path/src/txt/state"
v="monero-bash-${MONERO_BASH_VER}.tar"

# clean
cd "/tmp"
[[ -e "$v" ]]&& rm "$v"
[[ -e SHA256SUM ]]&& rm SHA256SUM
[[ -e SHA256SUM.asc ]]&& rm SHA256SUM.asc

# tar
tar -cf "$v" "monero-bash"
rm -rf monero-bash

# hash + sign
sha256sum "$v" > SHA256SUM
gpg --clearsign SHA256SUM
rm SHA256SUM
mv SHA256SUM.asc SHA256SUM

# check hash + sign
gpg --verify SHA256SUM &>/dev/null && echo "sign OK"  || echo "sign FAIL"
sha256sum -c SHA256SUM &>/dev/null && echo "hash OK" || echo "hash FAIL"

# copy changelog/sign to clipboard
CLIP() {
	grep -B999 -m2 "^$" CHANGELOG.md
	echo "## SHA256SUM & [PGP Signature](https://github.com/hinto-janaiyo/monero-bash/blob/main/gpg/hinto-janaiyo.asc)"
	echo '```'
	cat SHA256SUM
	echo '```'
}
CLIP | xclip -selection clipboard
echo "changelog copied to clipboard"
rm SHA256SUM
rm CHANGELOG.md
