#!/usr/bin/env bash
#
# script to create new monero-bash releases
set -e

# git folder
path="$HOME/git/monero-bash"

# copy to tmp
rm -fr "/tmp/monero-bash"
cp -fr "$path" "/tmp/"

# remove non-release files
cd "/tmp/monero-bash"
rm -fr docs .git tests .gitignore LICENSE README.md
mv -f CHANGELOG.md /tmp/CHANGELOG.md

# version
source "$path/src/txt/state"
v="monero-bash-${MONERO_BASH_VER}.tar"

# clean
cd "/tmp"
[[ -e "$v" ]]&& rm "$v"
[[ -e SHA256SUM ]]&& rm SHA256SUM
[[ -e SHA256SUM.asc ]]&& rm SHA256SUM.asc

# tar
tar -cf "$v" "monero-bash"
rm -rf monero-bash

# hash + sign
sha256sum "$v" > SHA256SUM
gpg --clearsign SHA256SUM
rm SHA256SUM
mv SHA256SUM.asc SHA256SUM

