#!/usr/bin/env bash
#
#						master source file that sources all of /monero-bash/src/
#
# global variables
source "$installDirectory/src/var" || varMissing="true"

# global functions
for functions in $installDirectory/src/func/* ;do
	source "$functions" || funcMissing="true"
done

# config file
source "$installDirectory/config" || configMissing="true"

# debug file
source "$installDirectory/src/debug" || debugMissing="true"

# state file
source "$installDirectory/src/txt/state" || stateMissing="true"

# hashlist file
if [[ ! -f  "$installDirectory/src/txt/hashlist" ]]; then
	 hashlistMissing="true"
fi
