#!/usr/bin/env bash
#
#						master source file
#

#
#						NEEDED SOURCE FILES
#
# global variables
source "$installDirectory/src/var" || varMissing="true"

# global functions
for functions in $installDirectory/src/func/* ;do
	source "$functions" || funcMissing="true"
done

# debug file
source "$installDirectory/src/debug" || debugMissing="true"

# state file
source "$installDirectory/src/txt/state" || stateMissing="true"

# hashlist file
if [[ ! -f  "$installDirectory/src/txt/hashlist" ]]; then
	hashlistMissing="true"
fi

#
#						USER FILES
#
# config file
source "$MONERO_BASH_FOLDER/config/monero-bash" || configMissing="true"
