#!/usr/bin/env bash
#
# debugging tools for monero-bash
# USE VERY CAREFULLY
#

# invoke a monero-bash function directly
DEBUG()
{
	$iwhite; echo -n "input: "
	read command
	"$command"
}

# list all monero-bash functions, variables
LIST()
{
	echo -e "\033[1;32mMONERO-BASH GLOBAL FUNCTIONS:\033[0m"
	declare -F | sed 's/declare -f //g'
	echo -e "\033[1;33mMONERO-BASH GLOBAL VARIABLES:\033[0m"
	cat "src/var" | grep -v "#" | grep -v "\033"
}

# produce a hash list for important monero-bash files /monero-bash/src/txt/hashlist
PRODUCE_HASH_LIST()
{
	echo "producing $hashlist"
	echo -n > "$hashlist"
	# monero-bash hash
	sha256sum "monero-bash" >> "$hashlist"
	# src file hashes
	for i in src/* ;do
		if [[ -f "$i" ]]; then
			sha256sum $i >> "$hashlist"
		fi
	done
	# function hashes
	for i in src/func/* ;do
		if [[ -f "$i" ]]; then
			sha256sum $i >> "$hashlist"
		fi
	done
	# txt hashes
	for i in src/txt/* ;do
		if [[ -f "$i" && "$i" != "src/txt/hashlist" ]]; then
			sha256sum $i >> "$hashlist"
		fi
	done
}

# check hash list against current monero-bash files (with color coded output)
CHECK_HASH_LIST()
{
	# monero-bash hash
	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
	if [[ $? = "0" ]]; then
		echo -n "monero-bash: "
		$igreen; echo "OK" ;$white
	else
		echo -n "monero-bash: "
		$bred; echo "FAILED" ;$white
		hashFail="true"
	fi
	# src file hashes
	for i in src/* ;do
		if [[ -f "$i" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			if [[ $? = "0" ]]; then
				echo -n "$i: "
				$igreen; echo "OK" ;$white
			else
				echo -n "$i: "
				$bred; echo "FAILED" ;$white
				hashFail="true"
			fi
		fi
	done
	# function hashes
	for i in src/func/* ;do
		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
		if [[ $? = "0" ]]; then
			echo -n "$i: "
			$igreen; echo "OK" ;$white
		else
			echo -n "$i: "
			$bred; echo "FAILED" ;$white
			hashFail="true"
		fi
	done
	# txt hashes
	for i in src/txt/* ;do
		if [[ $i != "src/txt/hashlist" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			if [[ $? = "0" ]]; then
				echo -n "$i: "
				$igreen; echo "OK" ;$white
			else
				echo -n "$i: "
				$bred; echo "FAILED" ;$white
				hashFail="true"
			fi
		fi
	done
	if [[ $hashFail = "true" ]]; then
		$bred; echo -n "monero-bash error: "
		$bwhite; echo "hash check has failed"
		$white; echo "Exiting for safety..."
		exit 1
	else
		$bwhite; echo -n "monero-bash: "
		$bgreen; echo "hash check success!"
	fi
}
