#!/usr/bin/env bash
#
# debugging tools for monero-bash
# USE VERY CAREFULLY
#

# invoke a monero-bash function directly
DEBUG_04e3be9()
{
	$bred; echo "@@@@@@   DEBUG MODE - BE CAREFUL   @@@@@@"
	$iwhite; echo -n "function to execute: " ;$off
	read command
	"$command"
}

# list all monero-bash functions, variables
LIST()
{
	echo -e "\033[1;32mMONERO-BASH GLOBAL FUNCTIONS:\033[0m"
	declare -F | sed 's/declare -f //g'
	echo -e "\033[1;33mMONERO-BASH GLOBAL VARIABLES:\033[0m"
	cat "src/var" | grep -v "#" | grep -v "\033"
}

# puts installed packages into variables
#WHICH_PACKAGES()
#{
#	
#}

# produce a hash list for important monero-bash files /monero-bash/src/txt/hashlist
PRODUCE_HASH_LIST()
{
	prompt_Sudo
	echo "producing $hashlist"
	sudo echo -n > "$hashlist"
	# monero-bash hash
	sudo sha256sum "monero-bash" >> "$hashlist"
	# src file hashes
	for i in src/* ;do
		if [[ -f "$i" ]]; then
			sudo sha256sum $i >> "$hashlist"
		fi
	done
	# function hashes
	for i in src/func/* ;do
		if [[ -f "$i" ]]; then
			sudo sha256sum $i >> "$hashlist"
		fi
	done
	# txt hashes
	for i in src/txt/* ;do
		if [[ -f "$i" && "$i" != "src/txt/hashlist" ]]; then
			sudo sha256sum $i >> "$hashlist"
		fi
	done
}

# check hash list against current monero-bash files (with color coded output)
CHECK_HASH_LIST()
{
	# monero-bash hash
	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
	if [[ $? = "0" ]]; then
		echo -n "monero-bash: "
		$bgreen; echo "OK" ;$white
	else
		echo -n "monero-bash: "
		$bred; echo "FAILED" ;$white
		hashFail="true"
	fi
	# src file hashes
	for i in src/* ;do
		if [[ -f "$i" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			if [[ $? = "0" ]]; then
				echo -n "$i: "
				$bgreen; echo "OK" ;$white
			else
				echo -n "$i: "
				$bred; echo "FAILED" ;$white
				hashFail="true"
			fi
		fi
	done
	# function hashes
	for i in src/func/* ;do
		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
		if [[ $? = "0" ]]; then
			echo -n "$i: "
			$bgreen; echo "OK" ;$white
		else
			echo -n "$i: "
			$bred; echo "FAILED" ;$white
			hashFail="true"
		fi
	done
	# txt hashes
	for i in src/txt/* ;do
		if [[ $i != "src/txt/hashlist" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			if [[ $? = "0" ]]; then
				echo -n "$i: "
				$bgreen; echo "OK" ;$white
			else
				echo -n "$i: "
				$bred; echo "FAILED" ;$white
				hashFail="true"
			fi
		fi
	done
	if [[ $hashFail = "true" ]]; then
		$bred; echo -n "monero-bash error: "
		$bwhite; echo "hash check has failed"
		$white; echo "Exiting for safety..."
		exit 1
	else
		$bwhite; echo -n "monero-bash: "
		$bgreen; echo "hash check success!"
	fi
}

# checks the hash list less verbosely
QUIET_HASH_LIST()
{
	# monero-bash hash
	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
	if [[ $? = "0" ]]; then
		echo -n "monero-bash: "
		$bgreen; echo "OK" ;$white
	else
		echo -n "monero-bash: "
		$bred; echo "FAILED" ;$white
		hashFail="true"
	fi
	# src file hashes
	for i in src/* ;do
		if [[ -f "$i" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			[[ $? != "0" ]]&& srcHashFail="true"
		fi
	done
	if [[ $srcHashFail = "true" ]]; then
		$white; echo -n "source: "
		$bred; echo "FAILED"
	else
		$white; echo -n "source: " ;$white
		$bgreen; echo "OK" ;$white
	fi
	# function hashes
	for i in src/func/* ;do
		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
		[[ $? != "0" ]]&& funcHashFail="true"
	done
	if [[ $funcHashFail = "true" ]]; then
		$white; echo -n "functions: "
		$bred; echo "FAILED"
	else
		$white; echo -n "functions: " ;$white
		$bgreen; echo "OK" ;$white
	fi
	# txt hashes
	for i in src/txt/* ;do
		if [[ $i != "src/txt/hashlist" ]]; then
			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
			[[ $? != "0" ]]&& txtHashFail="true"
		fi
	done
	if [[ $txtHashFail = "true" ]]; then
		$white; echo -n "text: "
		$bred; echo "FAILED"
	else
		$white; echo -n "text: " ;$white
		$bgreen; echo "OK" ;$white
	fi
	# if any fail, print error
	if [[ $hashFail = "true" || $srcHashFail = "true" || $funcHashFail = "true" || $txtHashFail = "true" ]]; then
		$bred; echo -n "monero-bash error: "
		$bwhite; echo "hash check has failed"
		$white; echo "Exiting for safety..."
		exit 1
	else
		$bwhite; echo -n "monero-bash: "
		$bgreen; echo "hash check success!"
	fi
}
