#!/usr/bin/env bash
#
# MASTER SOURCE FILE
#

# global variables
source "$installDirectory/src/var" 2>/dev/null || varMissing="true"

# global functions
for functions in "$installDirectory/src/func/"* ;do
	source "$functions" 2>/dev/null || funcMissing="true"
done

# debug file
source "$installDirectory/src/debug" 2>/dev/null || debugMissing="true"

# state file
source "$installDirectory/src/txt/state" 2>/dev/null || stateMissing="true"

# hashlist file
if [[ ! -f  "$installDirectory/src/txt/hashlist" ]]; then
	hashlistMissing="true"
fi

# monero-bash config
source "$config/monero-bash.conf" 2>/dev/null || configMissing="true"
