#!/usr/bin/env bash
#
#                       Global Variables
#
# file/folder paths
usrLocalShare="/usr/local/share"
dotMoneroBash="$HOME/.monero-bash"
config="$dotMoneroBash/config"
wallets="$dotMoneroBash/wallets"
bitMonero="$dotMoneroBash/.bitmonero"
old="$installDirectory/old"
bin="$installDirectory/bin"
binMonero="$bin/monero"
binXMRig="$bin/xmrig"
binP2Pool="$bin/p2pool"
hashlist="$installDirectory/src/txt/hashlist"
state="$installDirectory/src/txt/state"
sysd="/etc/systemd/system"
xmrigConf="$config/xmrig.json"
p2poolConf="$config/p2pool.json"

#
#						Colors
#
# regular
black="printf \033[0;30m"
red="printf \033[0;31m"
green="printf \033[0;32m"
yellow="printf \033[0;33m"
blue="printf \033[0;34m"
purple="printf \033[0;35m"
cyan="printf \033[0;36m"
white="printf \033[0;37m"
# bold
bblack="printf \033[1;90m"
bred="printf \033[1;91m"
bgreen="printf \033[1;92m"
byellow="printf \033[1;93m"
bblue="printf \033[1;94m"
bpurple="printf \033[1;95m"
bcyan="printf \033[1;96m"
bwhite="printf \033[1;97m"
# underscore
ublack="printf \033[4;30m"
ured="printf \033[4;31m"
ugreen="printf \033[4;32m"
uyellow="printf \033[4;33m"
ublue="printf \033[4;34m"
upurple="printf \033[4;35m"
ucyan="printf \033[4;36m"
uwhite="printf \033[4;37m"
# high intensity
iblack="printf \033[0;90m"
ired="printf \033[0;91m"
igreen="printf \033[0;92m"
iyellow="printf \033[0;93m"
iblue="printf \033[0;94m"
ipurple="printf \033[0;95m"
icyan="printf \033[0;96m"
iwhite="printf \033[0;97m"
# no color
off="printf \033[0m"
