#!/usr/bin/env bash
#
#                       Global Variables
#
# timestamp for .old folder
currentDayTime="$(date '+%Y-%m-%d@%H-%M-%S')"
# file/folder paths
usrLocalShare="/usr/local/share"
dotMoneroBash="$HOME/.monero-bash"
bin="$dotMoneroBash/bin"
binMonero="$bin/monero"
binXMRig="$bin/xmrig"
binP2Pool="$bin/p2pool"
config="$dotMoneroBash/config"
wallets="$dotMoneroBash/wallets"
bitMonero="$dotMoneroBash/.bitmonero"
old="$dotMoneroBash/.old"
tmp="$dotMoneroBash/.04e3be91e8aa36a61189a485ad6059b5f244a9de3cac8424876b66250ecb8ea0"
hashlist="$installDirectory/src/txt/hashlist"
state="$installDirectory/src/txt/state"
#####################################################################################################
# the "$tmp" folder is a unique hash instead of ".tmp" so that if some dude made a folder called    #
# ".tmp" inside /monero-bash/, i wouldnt delete it. please note: the folder with that hash name     #
# WILL BE DELETED when invoking the upgrade command.                                                #
#                                                                                                   #
# the actual sha256 hash:                                                                           #
# "04e3be91e8aa36a61189a485ad6059b5f244a9de3cac8424876b66250ecb8ea0"                                #
# is the result of hashing the 25 english seed phrase of a                                          #
# monero wallet i made that contains "0.5XMR" (as of 2022-march-22)                                 #
#                                                                                                   #
# sha256 isnt preferred for serious password hashing, but the real entropy comes from the seed.     #
# at the time of the wallets creation, 1626 english words were available for monero.                #
# this means there are 1626^25 different possible wallet seeds. if you have enough computational    #
# power to create all of them and check them against this hash, you might as well crack bitcoin or  #
# take over the world or something.                                                                 #
#                                                                                                   #
# anyway, good luck cracking it !                                                                   #
#                                                                                                   #
# address:                                                                                          #
# "46F6Se9qcYZ8MfiaRDn21c8PzE14xjrRcBrxHo4xHhTzRniKNLsZJtMh8xCM44aSpnKtGvU9ZtokNgGdZU1jfCWJVqyx14t" #
# private view key:                                                                                 #
# "700aaa8803452c441e041be5c2a4ffc8515261962b80128eab3f233bd97cfc0a"                                #
#####################################################################################################

#
#						Colors
#
# regular
black="printf \033[0;30m"
red="printf \033[0;31m"
green="printf \033[0;32m"
yellow="printf \033[0;33m"
blue="printf \033[0;34m"
purple="printf \033[0;35m"
cyan="printf \033[0;36m"
white="printf \033[0;37m"
# bold
bblack="printf \033[1;30m"
bred="printf \033[1;31m"
bgreen="printf \033[1;32m"
byellow="printf \033[1;33m"
bblue="printf \033[1;34m"
bpurple="printf \033[1;35m"
bcyan="printf \033[1;36m"
bwhite="printf \033[1;37m"
# underscore
ublack="printf \033[4;30m"
ured="printf \033[4;31m"
ugreen="printf \033[4;32m"
uyellow="printf \033[4;33m"
ublue="printf \033[4;34m"
upurple="printf \033[4;35m"
ucyan="printf \033[4;36m"
uwhite="printf \033[4;37m"
# high intensity
iblack="printf \033[0;90m"
ired="printf \033[0;91m"
igreen="printf \033[0;92m"
iyellow="printf \033[0;93m"
iblue="printf \033[0;94m"
ipurple="printf \033[0;95m"
icyan="printf \033[0;96m"
iwhite="printf \033[0;97m"
# no color
off="printf \033[0m"
